---
title: "`r paste('Norsk register for invasiv kardiologi (NORIC)', 'Månedsrapport: Aortaklaff for ', params$hospitalName) `"
params:
  author: ukjent forfatter
  hospitalName: ukjent sykehus
  tableFormat: html
  reshID: 999999
  registryName: rapbase
  userFullName: Ukjent bruker
  userRole: ukjent rolle
  rendered_by_shiny: FALSE
header-includes:
- \usepackage[english, norsk]{babel}
- \usepackage{booktabs}
- \usepackage{rotating}
- \usepackage{float}
abstract: '`r paste0("Denne rapporten er generert ved hjelp av resultatløsningen _Rapporteket_ og er kun ment til internt bruk!", "\\newline ", "\\newline ", "Rapporten inneholder tabeller og figurer med resultater basert på forløp registrert ved ", params$hospitalName, ". Opptellinger og statistikker er gjort per forløp/prosedyre, og ikke per individ. Tabellene og figurene presenteres med data fra de siste 14 månedene." , "\\newline ", "\\newline ", "Eventuelle spørsmål knyttet til rapporten kan rettes til [noric@helse-bergen.no](mailto:noric@helse-bergen.no)") `'
date: '`r format(Sys.time(), "%d. %B, %Y")`'
registryName: NORIC
regtext: '`r readLines(system.file("registryShortDescription.txt", package = "noric"))`'
reglogo: '`r system.file("logoNORIC.png", package = "noric")`'
userFullName: '`r params$userFullName`'
linkcolor: darkblue
output:
  fig_caption: yes
---

```{r knitrOptions, include=FALSE}
library(magrittr)
library(knitr)
library(kableExtra)
library(dplyr)
library(janitor)

options(knitr.table.format = params$tableFormat)

knitr::opts_chunk$set(warnings = FALSE, echo = FALSE)
options(stringsAsFactors = FALSE)

# For some reason Shiny Server does not get the server locale settings right.
# To display dates correct, enforce locale here:
Sys.setlocale("LC_TIME", "nb_NO.UTF-8")
``` 


```{r SKDEcol, include=FALSE}

colPrimary <- c("#000059",
                "#084594",
                "#2171b5",
                "#4292c6",
                "#6baed6",
                "#c6dbef")
colNeutral <- c("#4D4D4D", "#737373", "#A6A6A6", "#DADADA")
colKontrast <- "#FF7260"

``` 

```{r parametre}
showN <- 14
```


```{r }
if (params$rendered_by_shiny == TRUE && params$tableFormat == "latex")
    shiny::setProgress(0.05)  # set progress to 5%
```


```{r latest_entry, include=FALSE, eval=TRUE}
# DATAGRUNNLAG: PERIODE FOR SQL SPØRRING

# NYESTE DATO:
# Finne nyeste prosedyredato (=nyeste registrering). Vi ønsker ikke at
# forhåndsregisrerte planlagte forløp kommer med i rapporten. Derfor brukes
# gårsdagens dato som referanse, ingen forløp etter denne kommer med .
# Vi vil dermed også kunne se dersom ingen nye registreringer gjøres eller om
# overføringer har stoppet opp

# ELDSTE DATO:
# Januar fra i fjor (hele foregående år skal vise i rapporten)

if(params$registryName %in% "noricStagingNasjonal"){
  nyeste_reg <- noric::getLatestEntryHospital(
    registryName = params$registryName, 
    reshID = params$reshID)
  
} else {
  nyeste_reg <- noric::getLatestEntry(registryName = params$registryName)
}

periode_data <- data.frame(
  siste_dato = min((as.Date(Sys.time()) - 1),
                   nyeste_reg))

periode_data %<>%
  dplyr::mutate(
    forste_dato  = lubridate::floor_date(.data$siste_dato,
                                         "month") - months(showN))
```

```{r monthTabPrepare, include=FALSE, eval=TRUE}

timeTableMonth <- data.frame(
  monthDato = seq(periode_data$forste_dato, 
                  periode_data$siste_dato,
                  by = "month")) %>% 
  dplyr::transmute(maaned = as.factor(format(x = .data$monthDato, 
                                             format = "%Y-%m"))) %>% 
  dplyr::mutate(maaned = as.ordered(maaned))


rangeProsDato <- paste(format(periode_data$forste_dato, 
                              "%d/%m-%Y"), 
                       "til", 
                       format(periode_data$siste_dato, 
                              "%d/%m-%Y"))
```



```{r GetData, include=FALSE, cache=FALSE}

if(params$registryName %in% "noricStagingNasjonal"){
  # SPørring til NASJONAL database. 
  # Kun utvalgt sykehus
  AK <- noric::getPrepAkData(registryName = params$registryName,
                             fromDate  = periode_data$forste_dato,
                             toDate = periode_data$siste_dato,
                             singleRow = FALSE, 
                             singleHospital = params$reshID)
  
  } else{
    # SPørring til LOKAL database. 
    # Kun et sykehus, som er registry name
    AK <- noric::getPrepAkData(registryName = params$registryName,
                               fromDate  = periode_data$forste_dato,
                               toDate = periode_data$siste_dato,
                               singleRow = FALSE, 
                               singleHospital = NULL)
}   


```


```{r }
if (params$rendered_by_shiny == TRUE && params$tableFormat == "latex")
    shiny::setProgress(0.1)  # set progress to 10%
```



`r if(params$tableFormat !="html") {"<!--"}`
# Månedsrapport: Prosedyrer på aortaklaff {-}
Denne rapporten er generert ved hjelp av resultatløsningen *Rapporteket* og er kun ment til internt bruk! 
<br/> <br/>
Rapporten inneholder tabeller og figurer med resultater basert på forløp registrert ved `r params$hospitalName`. Opptellinger og statistikker er gjort per forløp/prosedyre, og ikke per individ. Tabellene og figurene presenteres med data fra perioden `r rangeProsDato`.
<br/><br/>
Eventuelle spørsmål knyttet til rapporten kan rettes til [noric@helse-bergen.no](mailto:noric@helse-bergen.no)
`r if(params$tableFormat !="html") {"-->"}`


`r if(params$tableFormat !="latex") {"<!--"}`
\newpage
`r if(params$tableFormat !="latex") {"-->"}`

<br/><br/>

# Prosedyren

## Prosedyretype {#prosedyretype}
Variabelen _prosedyre_ er ny fra februar 2023. 
```{r FigNProsedyreType, fig.cap =  paste0("Antall prosedyrer på aortaklaff registrert i NORIC per måned ved ", params$hospitalName, " i perioden ", rangeProsDato ,  "."), fig.width = 8, fig.height = 5,  fig.pos = "H", fig.align = "center", out.width = "\\textwidth"}

pal <- colPrimary[c(5, 3, 1)]


prosedyreTypeMaaned <- AK %>%
  dplyr::count(.data$maaned,
               .data$ProsedyreType) %>%
  dplyr::group_by(.data$maaned, .data$ProsedyreType)

prosedyreType_levels <- c("Angio", "Angio + PCI", "PCI")

prosedyreTypeMaaned %>% ggplot2::ggplot(
  ggplot2::aes(x = .data$maaned,
               y = .data$n,
               fill = factor(.data$ProsedyreType,
                             levels = prosedyreType_levels))
) +
  ggplot2::geom_bar(position = "stack", stat = "identity") +
  ggplot2::scale_fill_manual(values = pal) +
  ggplot2::theme_minimal() +
  ggplot2::xlab("") +
  ggplot2::ylab("Antall prosedyrer") +
  ggplot2::theme(legend.title = ggplot2::element_blank(),
                 axis.text = ggplot2::element_text(size = 12),
                 axis.text.x = ggplot2::element_text(angle = 45, hjust = 1), 
                 axis.title = ggplot2::element_text(size = 12), 
                 legend.text = ggplot2::element_text(size = 12))

```



