## code to prepare `map_num_tekst` dataset goes here

varnavn_kobl <- 
  data.frame(
    kol = 
      c("MCE.MCEID AS ForlopsID",
        "MCE.PARENT_MCEID AS PrimaerForlopsID",
        "P.ID AS PasientID",
        "P.SSN_TYPE AS FnrType",
        "A.CENTREID AS AvdRESH",
        "A.INTERDAT AS ProsedyreDato",
        "A.INTERDAT_TIME AS ProsedyreTid",
        "A.INTERDAT_TIME_MISSING AS ProsedyreTidUkjent",
        "A.REGTYP AS ProsedyreType",
        "MCE.ACUTE_ELECTIVE AS Hastegrad",
        "P.GENDER AS Kjonn",
        "P.BIRTH_DATE AS FodselsDato",
        "P.DECEASED  AS Avdod",
        "P.DECEASED_DATE AS AvdodDato",
        "P.REGISTERED_DATE AS PasientRegDato",
        "A.SYMPTOM_ONSET_DATE AS SymptomDato",
        "A.SYMPTOM_ONSET_TIME AS SymptomTid",
        "A.PREHOSPITAL_ECG_DATE AS BesUtlEKGDato",
        "A.PREHOSPITAL_ECG_TIME AS BesUtlEKGTid",
        "A.PREHOSPITAL_ECG_TIME_MISSING AS BesUtlEKGTidUkjent",
        "A.JOURTID AS Vakttid",
        "A.HEIGHT AS Hoyde",
        "A.WEIGHT AS Vekt",
        "A.SKREATININ AS SKreatinin",
        "A.TIDPCI  AS TidlPCI",
        "A.TIDCABG  AS TidlABC",
        "A.SMOKING_STATUS  AS RoykeStatus",
        "A.HYPERTON  AS BehHypertoni",
        "A.STATINS AS Statiner",
        "A.TIDINF  AS TidlInfarkt",
        "A.HISTORY_OF_CHF  AS KjentNedsattVenstVentr",
        "A.DIABETES  AS Diabetes",
        "A.DIABETESINSULIN AS Insulin",
        "A.PREVIOUS_STROKE AS TidligereSlag",
        "A.PERIPHERAL_VASCULAR_DISEASE  AS PeriferKarsykdom",
        "A.INDIKATION  AS Indikasjon",
        "A.MYOKARD  AS Myokardskademarkor",
        "A.STSEGSANK  AS STSegmentSenkning",
        "A.STAGED_PROCEDURE  AS StegvisProsedyre",
        "A.CSS AS CanadianClass",
        "A.NYHA AS NYHA",
        "A.CARD AS KardiogentSjokk",
        "A.KILLIPKLASS AS KillipKlasse",
        "A.FYND AS Funn",
        "A.ADMISSION_ER AS AnkomstPCIDato",
        "A.ADMISSION_ER_TIME AS AnkomstPCITid",
        "A.ADMISSION_ER_TIME_MISSING AS AnkomstPCITidUkjent",
        "A.PUNKT AS Stikksted",
        "A.STENOS AS StenoseTidlBehSegment",
        "A.CABG AS StenoseACBGraft",
        "A.STRESSKARDIOMYOPATI  AS Stresskardiomyopati",
        "A.PRIMBES AS PrimarBeslutning",
        "A.DIAGNOSTIK AS AnnenDiagHovedSpm",
        "A.DIATRYCK AS FFR",
        "A.DIADOP AS Doppler",
        "A.DIAIVUS AS IVUS",
        "A.DIAOCT AS OCT",
        "A.DIAIFR AS IFR",
        "A.DIANIRS AS NIRS",
        "A.DIACFR AS CFR",
        "A.DIAIMR AS IMR",
        "A.DIAPDPA AS PDPA",
        "A.DIAPAHYPEREMI AS PA_Hyperemi",
        "A.DIAPDHYPEREMI AS PD_Hyperemi",
        "A.DIAANN AS AnnenDiag",
        "A.EXTRAPROC AS Tilleggsprosedyrer",
        "A.CARDIAC_CATHETERIZATION AS HoyreHjerteKat",
        "A.VALVE_RECORDING AS Ventilfilming",
        "A.PERICARDIOCENTESIS AS Perikardiocentese",
        "A.ADJUVANT AS AdjuvantTerapi",
        "A.ADJPUMP AS Aortaballongpumpe",
        "A.ADJIMPELLA AS Impella",
        "A.ADJECMO AS ECMO",
        "A.ADJKAM AS AnnenVenstreKammerAssist",
        "A.ADJLUK AS MekKompr",
        "PCI.ADJDISTAL AS DistalProtectionDevice",
        "A.ADJPACE AS Pacemaker",
        "PCI.ADJTROMB AS Trombectomy",
        "A.ADJPTA AS PTAHalskar",
        "A.ADJPTSMA AS PTSMA",
        "A.ADJANN AS AnnenAdj",
        "A.OPEN_CAPILLARY AS ApningKarDato",
        "A.OPEN_CAPILLARY_TIME AS ApningKarTid",
        "A.OPEN_CAPILLARY_TIME_MISSING AS ApningKarTidUkjent",
        "A.OPEN_CAP_OPEN_ANGIO AS KarAapentVedAngio",
        "A.OPEN_CAP_OPEN_UNSUCCESSFUL AS KarIkkeAapnet",
        "PCI.SUCCESS AS GenereltSuksess",
        "A.LABNO AS LabNummer",
        "A.STRALDOS AS Straledose",
        "A.GENOMLYSNINGSTID AS GjenLysTidSek",
        "A.KONTRASTMEDEL AS Kontrastmiddel",
        "A.KONTRASTMEDELMANGD AS KontrastMengdeMl",
        "A.ANNANKONTRASTUNDERSOK  AS AnnKonMidUndersokelse",
        "A.VASCCLOSUREDEV AS ArteriellLukning",
        "A.LABKOMP  AS LabKomplikasjon",
        "A.LABALLERGILATT  AS LabKompAllergiskLettModerat",
        "A.LABALLERGIALLV  AS LabKompAllergiskAlvorlig",
        "A.LABBEHARYTMI  AS LabKompBehkrevendeArytmi",
        "A.LABHEMO  AS LabKompHemodynamisk",
        "A.LABNEURO  AS LabKompNeurologisk",
        "A.LABVASK  AS LabKompVaskulaerIkkeKoronar",
        "A.LABTAPPAT  AS LabKompMistetStent",
        "A.LABBESTSIDO  AS LabKompVedvarSidegrensokkl",
        "A.LABPERF  AS LabKompPerforasjon",
        "A.LABTAMP  AS LabKompTamponade",
        "A.LABAKUTCABG  AS LabKompAkuttACBOperasjon",
        "A.LABANNANALLV  AS LabKompAnnenAlv",
        "A.LABDODSFALL  AS LabKompDod",
        "A.LABPROCEDURDOD  AS LabKompProsedyrerelatertDod",
        "I.TRANSFERREDPATIENT  AS OverflyttetFra",
        "I.REFERRING_HOSP_ADMISSIONDATE AS InnleggelseHenvisendeSykehusDato",
        "I.REFERRING_HOSP_ADMISSIONDATE_MISSING AS InnleggelseHenvisendeSykehusDatoUkjent",
        "I.REFERRING_HOSP_ADMISSIONDATE_TIME AS InnleggelseHenvisendeSykehusTid",
        "I.REFERRING_HOSP_ADMISSIONDATE_TIME_MISSING AS InnleggelseHenvisendeSykehusTidUkjent",
        "I.PRESENTING_SYMPTOMS AS Innkomstarsak",
        "I.SYMPTOM_ONSET_DATE AS SymptomdebutDato",
        "I.SYMPTOM_ONSET_TIME AS SymptomdebutTid",
        "I.CPR_BEFORE_HOSPITAL  AS HLRForSykehus",
        "I.ECG_RHYTHM AS EKGRytme",
        "I.ECG_QRS_ANNOTATION AS EKGQRS",
        "I.ECG_STT_CHANGES AS EKGSTT",
        "I.LEFT_BLOCK  AS VenstreGrenblokk",
        "I.ECG_DECISION_TRIGGERING AS BeslutningsutlosendeEKG",
        "I.PREHOSPITAL_ECG_DATE AS BeslEKGDato",
        "I.PREHOSPITAL_ECG_TIME AS BeslEKGTid",
        "I.PREHOSPITAL_ECG_TIME_MISSING AS BeslEKGUkjent",
        "I.HEART_RATE AS Hjertefrekvens",
        "I.SYSTOLIC_BLOOD_PRESSURE AS SystoliskBlodtrykk",
        "I.DIASTOLIC_BLOOD_PRESSURE AS DiastoliskBlodtrykk",
        "I.KILLIPKLASS AS KillipKlasseAnkomst",
        "I.CARDIAC_SHOCK  AS KardiogentSjokkAnkomst",
        "A.REPERTREATMENT AS GittTrombolyse",
        "A.TYPE_THROMB_THERAPY_ADM AS TrombolyseMedikament",
        "A.THROMB_GIVEN_DATE AS TrombolyseDato",
        "A.THROMB_GIVEN_TIME AS TrombolyseTid",
        "A.THROMB_GIVEN_TIME_MISSING AS TrombolyseUkjent",
        "I.PREVIOUS_ACB AS TidligereACBOp",
        "I.PRIOR_CARDIAC_SURGERY  AS AnnenTidlKirurgi",
        "I.HYPERTENSION AS Hypertoni",
        "I.ASPIRIN_REG AS InitASA",
        "I.ORAL_ANTICOAGULANTS_REG AS InitAntikoagulantia",
        "I.OTHER_ANTIPLATELET_REG AS InitAndrePlatehemmere",
        "I.STATINS_REG AS InitStatiner",
        "I.NSAID_REG AS InitNSAID",
        "I.ACE_INHIBITORS_REG AS InitACEHemmere",
        "I.ANGIOTENSIN_II_BLOCK_REG AS InitA2Blokkere",
        "I.BETA_BLOCKERS_REG AS InitBetaBlokkere",
        "I.CALCIUM_ANTAGONIST_REG AS InitCaHemmere",
        "I.DIAB_MED_ORAL AS InitDiabetesPrOral",
        "I.DIGITALIS_REG AS InitDigitalis",
        "I.DIURETICS_REG AS InitDiuretika",
        "I.ALDOSTERONBLOCKAD_IC AS InitAldosteronantagonist",
        "I.OTHER_LIPID_LOW_AGENTS_REG AS InitOvrigLipid",
        "I.NITRATES_REG AS InitNitroglycerin",
        "IL.BIOCHEMICAL_MARKER_TYPE AS Infarktmarkoer",
        "IL.BIOCHEMICAL_MARKER_VALUE AS InfarktMarkoerMax",
        "IL.CHOLESTEROL_TOTAL AS Kolesterol",
        "IL.TRIGLYCERIDES AS Triglycerider",
        "IL.HDL_CHOLESTEROL AS HDL",
        "IL.LDL_MEASURED AS MaaltLDL",
        "IL.B_GLUCOSE AS SGlukose",
        "IL.HBA1CMOL AS HbA1c",
        "IL.S_CREATININ AS Kreatinin",
        "IL.CRP AS CRP",
        "IL.HEMOGLOBIN AS Hemoglobin",
        "F.SEGMENT1_LAYER",
        "F.SEGMENT2_LAYER",
        "F.SEGMENT3_LAYER",
        "F.SEGMENT4_LAYER",
        "F.SEGMENT5_LAYER",
        "F.SEGMENT6_LAYER",
        "F.SEGMENT7_LAYER",
        "F.SEGMENT8_LAYER",
        "F.SEGMENT9_LAYER",
        "F.SEGMENT10_LAYER",
        "F.SEGMENT11_LAYER",
        "F.SEGMENT12_LAYER",
        "F.SEGMENT13_LAYER",
        "F.SEGMENT14_LAYER",
        "F.SEGMENT15_LAYER",
        "F.SEGMENT16_LAYER",
        "F.SEGMENT17_LAYER",
        "F.SEGMENT18_LAYER",
        "F.SEGMENT19_LAYER",
        "F.SEGMENT20_LAYER",
        "PCI.SEKBESLUT AS SekundaerBeslutning",
        "PCI.KOMPREV AS KomplettRevaskularisering",
        "PCI.ANTIFORE AS AntitrombotiskFor",
        "PCI.TROFORE AS TrombolyseFor",
        "PCI.ASAFORE AS ASAFor",
        "PCI.CLOFORE AS ClopidogrelFor",
        "PCI.PRAFORE AS PrasugrelFor",
        "PCI.TICFORE AS TicagrelorFor",
        "PCI.HEPFORE AS HeparinFor",
        "PCI.DALFORE AS DalteparinFor",
        "PCI.ENOFORE AS EnoxaparinFor",
        "PCI.ANNFORE AS AnnetLavmolHeparinFor",
        "PCI.BIVFORE AS BivalirudinFor",
        "PCI.FONFORE AS FondaparinuxFor",
        "PCI.ABCFORE AS AbciximabFor",
        "PCI.EPTFORE AS EptifibatidFor",
        "PCI.TIRFORE AS TirofibanFor",
        "PCI.WARFORE AS WarfarinFor",
        "PCI.DABFORE AS DabigatranFor",
        "PCI.APIFORE AS ApiksabanFor",
        "PCI.RIVFORE AS RivaroksabanFor",
        "PCI.EDOFORE AS EdoksabanFor",
        "PCI.KANGRELORFORE AS KangrelorFor",
        "PCI.OVRFORE AS AnnetAntitrombotiskFor",
        "PCI.ANTIFORE AS AntitrombotiskUnder",
        "PCI.TROUND AS TrombolyseUnder",
        "PCI.ASAUND AS ASAUnder",
        "PCI.CLOUND AS ClopidogrelUnder",
        "PCI.PRAUND AS PrasugrelUnder",
        "PCI.TICUND AS TicagrelorUnder",
        "PCI.HEPUND AS HeparinUnder",
        "PCI.DALUND AS DalteparinUnder",
        "PCI.ENOUND AS EnoxaparinUnder",
        "PCI.ANNUND AS AnnetLavmolHeparinUnder",
        "PCI.BIVUND AS BivalirudinUnder",
        "PCI.FONUND AS FondaparinuxUnder",
        "PCI.ABCUND AS AbciximabUnder",
        "PCI.EPTUND AS EptifibatidUnder",
        "PCI.TIRUND AS TirofibanUnder",
        "PCI.WARUND AS WarfarinUnder",
        "PCI.KANUND AS KangrelorUnder",
        "PCI.OVRFORE AS AnnetAntitrombotiskUnder",
        "C.AVDKOMP AS AvdKomp",
        "C.AVDALLERGISK AS AvdKompAllergisk",
        "C.AVDBLODNING AS AvdKompBlodning",
        "C.AVDBLODMAJOR AS AvdKompBlodningMajor",
        "C.AVDBLODMINOR AS AvdKompBlodningMinor",
        "C.AVDBEHPSEUDO AS AvdKompPseudoaneurysme",
        "C.AVDHEMATOM AS AvdKompHematomStor",
        "C.AVDHBFALL AS AvdKompHbFallStor",
        "C.AVDFORLANGDKOMPTID AS AvdKompForlengetTidStor",
        "C.AVDVARDTID AS AvdKompForlengetOppholdStor",
        "C.AVDULTRALJUD AS AvdKompUltralydCT",
        "C.AVDBLODTRANSFUSION AS AvdKompBlodtransfusjon",
        "C.AVDKIRURGISKATGARD AS AvdKompKirurgiskBeh",
        "C.AVDANNANBEHUTOVERKOMP AS AvdKompAnnenBehUtoverKompresjon",
        "C.AVDFORTIDAUTSATTNING AS AvdKompTidligUtsettelse",
        "C.AVDANNANVASK AS AvdKompVaskulaer",
        "C.AVDNEURO AS AvdKompNeurologiskKomp",
        "C.AVDNJURINSUFF AS AvdKompNyNyreinsuffisiens",
        "C.AVDTAMP AS AvdKompTamponade",
        "C.AVDREPCI AS AvdKompPCI",
        "C.AVDCABG AS AvdKompACB",
        "C.AVDHJARTINFARKT AS AvdKompHjerteinfarkt",
        "C.AVDANNANALLV AS AvdKompAnnenAlvorlig",
        "C.AVDDODSFALL  AS AvdKompDod",
        "C.AVDPROCEDURDOD AS AvdKompProsedyrerelatertDod",
        "C.CKMBFORE AS CKMBFor",
        "C.CKMBEFTER AS CKMBEtter",
        "C.TROPMETFORE AS TroponinMetFor",
        "C.TROPVARDEFORE AS TroponinVerdiFor",
        "C.TROPMETEFTER AS TroponinMetEtter",
        "C.TROPVARDEEFTER AS TroponinVerdiEtter",
        "D.DISCHARGE_DATE AS Utskrivningsdato",
        "D.DEATH  AS UtskrevetDod",
        "D.DECEASED_DATE AS UtskrevetDodsdato",
        "D.DISCHARGETO AS UtskrevetTil",
        "D.ASPIRIN_DISCHARGE AS ASA",
        "D.ORAL_ANTICOAGULANTS_DISCHARGE AS Antikoagulantia",
        "D.OTHER_ANTIPLATELET_DISCHARGE AS AndrePlatehemmere",
        "D.STATINS_DISCHARGE AS UtskrStatiner",
        "D.NSAID_DISCHARGE AS NSAID",
        "D.ACE_INHIBITORS_DISCHARGE AS ACEHemmere",
        "D.ANGIOTENSIN_II_BLOCK_DISCHARGE AS A2Blokkere",
        "D.BETA_BLOCKERS_DISCHARGE AS Betablokkere",
        "D.CALCIUM_ANTAGONIST_DISCHARGE  AS CaBlokkere",
        "D.DIAB_MED_INSULIN_DC  AS DiabetesBehandlingInsulin",
        "D.DIAB_MED_ORAL_DC AS DiabetesBehandlingPerOral",
        "D.DIGITALIS_DISCHARGE AS Digitalis",
        "D.DIURETICS_DISCHARGE AS Diuretika",
        "D.ALDOSTERONBLOCKAD_DC AS Aldosteronantagonister",
        "D.OTHER_LIPID_LOW_AGENTS_DISCHARGE AS OvrigeLipidsenkere",
        "D.NITRATES_DISCHARGE AS NitroglycerinLangtid",
        "D.OTHER_SERIOUS_DISEASE AS AnnenAlvorligSykdom",
        "D.INFARCTTYPE AS InfarktType",
        "D.INFARCTCLASSIFICATION AS InfarktSubklasse",
        "I.STATUS AS SkjemaStatusStart",
        "A.STATUS AS SkjemastatusHovedskjema",
        "D.STATUS AS SkjemaStatusUtskrivelse",
        "C.STATUS AS SkjemaStatusKomplikasjoner")
  ) |> tidyr::separate(col="kol", 
                       into=c("dbnavn", "rapporteket"), 
                       sep = " AS ") |> 
  tidyr::separate(col="dbnavn", 
                  into=c("tabell", "var_navn"), 
                  extra = "merge") |> 
  dplyr::mutate(rapporteket = ifelse(is.na(rapporteket), 
                                     var_navn, rapporteket),
                tabell = dplyr::case_when(tabell == "P" ~ "PATIENT",
                                          tabell == "A" ~ "REGANGIO",
                                          tabell == "I" ~ "INITIALCARE",
                                          tabell == "IL" ~ "INITIALCARE_LAB",
                                          tabell == "F" ~ "FINDINGSTATIC",
                                          tabell == "C" ~ "ANGIOPCICOMP",
                                          tabell == "D" ~ "DISCHARGE",
                                          .default = tabell),
                variabel_id = trimws(paste0(tabell, "_", var_navn))
  ) 

kodebok <- read.csv2(system.file("extdata/NORIC_klokeboken_18.03.2025.csv", 
                                 package = "noric")) |> 
  dplyr::select(type, listeverdier, listetekst, tabell, 
                fysisk_feltnavn, variabel_id)
mangler_kodebok_katvar <- varnavn_kobl |> 
  dplyr::filter(variabel_id %in% 
                  setdiff(varnavn_kobl$variabel_id, kodebok$variabel_id)) |> 
  dplyr::filter(tabell=="ANGIOPCICOMP") |> 
  dplyr::mutate(tabell=tolower(tabell)) |> 
  dplyr::rename(fysisk_feltnavn = var_navn) |> 
  dplyr::select(-rapporteket)
mangler_kodebok_katvar <- dplyr::bind_rows(mangler_kodebok_katvar,
                                           mangler_kodebok_katvar,
                                           mangler_kodebok_katvar) |> 
  dplyr::arrange(variabel_id)

mangler_kodebok_katvar <- dplyr::bind_cols(
  data.frame(type = rep("Listevariabel", 9),
             listeverdier = rep(c(0,1,9), 3),
             listetekst = rep(c("Nei", "Ja", "Ukjent"))),
  mangler_kodebok_katvar)

kodebok <- dplyr::bind_rows(kodebok, mangler_kodebok_katvar)
map_num_tekst <- merge(kodebok,
                       varnavn_kobl[, c("variabel_id", "rapporteket")],
                       by = "variabel_id", all.x = TRUE) |> 
  dplyr::arrange(variabel_id, rapporteket, listeverdier) |> 
  dplyr::select(rapporteket, listeverdier, listetekst) |> 
  dplyr::rename(variabel_id = rapporteket,
                verdi = listeverdier,
                verditekst = listetekst) |> 
  dplyr::filter(!is.na(verdi),
                !is.na(variabel_id))


usethis::use_data(map_num_tekst, overwrite = TRUE)
