
# Norsk register for invasiv kardiologi (NORIC)
## Ventetider ved NSTEMI
## `r AP$Sykehusnavn[1]`



```{r,knitrOptions,include=FALSE}
# knitr::knit2html("NORIC_local_monthly_NSTEMI_treatment_delay.Rmd")

knitr::opts_chunk$set(warnings=FALSE,echo=FALSE)
options(stringsAsFactors=FALSE , width = "130")


## START to be deleted
# In future, rapbase will take care of the following:
# make sure processing takes place "here" (sessions getwd())
knitr::opts_knit$set(root.dir='./')

# make sure we do not make figure folder
knitr::opts_chunk$set(fig.path='')
## END to be deleted

``` 



```{r,Prepare,include=FALSE}

# SKDE colors
colPrimary <- c("#000059", "#084594", "#2171b5", "#4292c6", "#6baed6", "#c6dbef")
colNeutral <- c("#4D4D4D", "#737373", "#A6A6A6", "#DADADA")
colKontrast <- "#FF7260"


# assuming that if reshID does *not*exist
#  it is a testrun on localhost

if ( exists( "reshID" ) ) {
    baseName <- "noricStaging"
    registryName <- noric::NORICmakeRegistryName(baseName, reshID)
    AP <- rapbase::LoadRegData(
        registryName = registryName ,
        query = "SELECT * FROM AngioPCIVar" ,
        dbType = "mysql")
} else {
    load("../data/noric_staging.Rd")
    AP <- subset( AP , Sykehusnavn == "Haukeland" )
}


AP$HenvisningsStatus <- car::recode(
    var = AP$OverflyttetFra ,
    recodes = "
        'Annet sykehus'='Overflyttet';
        'Nei, direkte inn til dette sykehus' = 'Direkte';
        'Omdirigert ambulanse' = 'Direkte';
        else = NA
        ")

AP$Indikasjon2 <- factor(
    car::recode(
        var = AP$Indikasjon ,
        recodes = "
            'Stabil koronarsykdom '='SAP';
            'UAP'='UAP';
            'NSTEMI'='NSTEMI';
            'STEMI'='STEMI';
            'Hjertestans ved STEMI'='STEMI';
            'STEMI > 24h'='STEMI';
            'STEMI/Rescue PCI'='STEMI';
            ' Uklare brystsmerter'='Uklare brystsmerter';
            else='Annet';
            ") ,
    levels = c("Uklare brystsmerter","SAP","UAP","NSTEMI","STEMI","Annet") )


AP$ProsedyreDato <- as.Date( AP$ProsedyreDato)

AP$Year <- as.numeric(
    format(
        x = AP$ProsedyreDato ,
        format = "%Y"))

AP$nMonth <- as.numeric(
    as.factor(
        format(
            AP$ProsedyreDato ,
            format = "%m")))

AP$Day <- as.numeric(
         AP$ProsedyreDato - min( AP$ProsedyreDato , na.rm = TRUE ) )

AP$Month <- as.factor(
    format(
        x = AP$ProsedyreDato ,
        format = "%Y-%m"))

AP$Week <- format(
    x = AP$ProsedyreDato ,
    format = "%Y-%W")



AP$InnleggelseHenvisendeSykehusDato <- as.Date( AP$InnleggelseHenvisendeSykehusDato)

AP$AnkomstPCIDato <- as.Date( AP$AnkomstPCIDato)

i.direkte <- which(AP$HenvisningsStatus == "Direkte")
AP$InnleggelseHenvisendeSykehusDato[ i.direkte ] <- AP$AnkomstPCIDato[ i.direkte ]

AP$DaysFromIndexAdmissionToProcedure <- as.numeric( AP$ProsedyreDato - AP$InnleggelseHenvisendeSykehusDato )

# AP[ 1:10 , c("DaysFromIndexAdmissionToProcedure","ProsedyreDato","InnleggelseHenvisendeSykehusDato","AnkomstPCIDato","HenvisningsStatus")]

AP$DaysFromPCIcenterAdmissionToProcedure <- as.numeric( AP$ProsedyreDato - AP$AnkomstPCIDato )

AP$DaysFromIndexAdmissionToProcedure[ which( AP$DaysFromIndexAdmissionToProcedure < 0 ) ] <- NA
AP$DaysFromIndexAdmissionToProcedure[ which( AP$DaysFromIndexAdmissionToProcedure > 50 ) ] <- NA

AP$DelayFromIndexAdmissionToProcedure <- cut(
    x = AP$DaysFromIndexAdmissionToProcedure ,
    breaks = c(0,1,3,50) ,
    labels = c("0-24","25-72",">72") ,
    include.lowest = TRUE
    )

AP$DaysFromIndexAdmissionToPCIcenter <- as.numeric(AP$AnkomstPCIDato - AP$InnleggelseHenvisendeSykehusDato )



NSTEMI <- subset(
    x = AP ,
    subset = (Indikasjon == "NSTEMI"))


``` 



```{r,Fig-R-NSTEMI-Delay,fig.cap="Prosentandel NSTEMI etter ventetid kategorie over tid",echo=FALSE,fig.pos='!h',fig.width=10,fig.height=4,out.width="\\textwidth"}

pal <- c( "#A8A8A8" , RColorBrewer::brewer.pal(3,"RdYlGn") )[4:1]
DelayLevels <- c( levels(NSTEMI$DelayFromIndexAdmissionToProcedure ) , "Mangler")

TabNDelay <- xtabs(
    formula = ~ addNA(DelayFromIndexAdmissionToProcedure) + Month ,
    data = NSTEMI)

TabRDelay <- 100 * prop.table(
                        x = TabNDelay ,
                        margin = 2 )

par(
    mar = c(3,10,2,10) ,
    xpd = NA ,
    las = 1)

xBarplot <- barplot(
    TabRDelay ,
    beside = FALSE ,
    horiz = FALSE ,
    axisnames = TRUE ,
    xlab = "Måned" ,
    col = pal )

text(
    x = xBarplot ,
    y = TabRDelay[1,] ,
    pos = 1 ,
    col = "#000000AA" ,
    labels = TabNDelay[1,])

text(
    x = xBarplot ,
    y = colSums(TabRDelay[1:2,]) ,
    pos = 1 ,
    col = "#000000AA" ,
    labels = TabNDelay[2,])

text(
    x = xBarplot ,
    y = colSums(TabRDelay[1:3,]) ,
    pos = 1 ,
    col = "#000000AA" ,
    labels = TabNDelay[3,])

legend(
    x = par("usr")[2] ,
    y = par("usr")[4]*.7 ,
    bty = "n" ,
    title = "Timer" ,
    legend = DelayLevels[4:1],
    fill = pal[4:1] )


```





```{r,Fig-R-NSTEMI-Delay-Transferred,fig.cap="Prosentandel NSTEMI overflyttet til PCI sykehus etter ventetid og sykehus ",echo=FALSE,fig.pos='!h',fig.width=10,fig.height=4,out.width="\\textwidth"}

TabNDelay <- xtabs(
    formula = ~ addNA(DelayFromIndexAdmissionToProcedure) + Month ,
    subset = HenvisningsStatus == "Overflyttet" ,
    data = NSTEMI)

TabRDelay <- 100 * prop.table(
                        x = TabNDelay ,
                        margin = 2 )


par(
    mar = c(3,10,2,10) ,
    xpd = NA ,
    las = 1)

xBarplot <- barplot(
    TabRDelayOrdered ,
    beside = FALSE ,
    horiz = TRUE ,
    border = FALSE ,
    xlab = "%" ,
    col = pal )

text(
    x = TabRDelayOrdered[1,] ,
    y = xBarplot ,
    pos = 2 ,
    col = "#000000AA" ,
    labels = TabNDelayOrdered[1,])

text(
    x = colSums(TabRDelayOrdered[1:2,]) ,
    y = xBarplot ,
    pos = 2 ,
    col = "#000000AA" ,
    labels = TabNDelayOrdered[2,])

text(
    x = colSums(TabRDelayOrdered[1:3,]) ,
    y = xBarplot ,
    pos = 2 ,
    col = "#000000AA" ,
    labels = TabNDelayOrdered[3,])


legend(
    x = par("usr")[2] ,
    y = par("usr")[4]*.7 ,
    bty = "n" ,
    title = "Timer" ,
    legend = DelayLevels ,
    fill = pal )

```


```{r}

fit.rqss <- function( tau , lambda )
    rqss(
        DaysFromIndexAdmissionToProcedure ~ qss(
            x = Day ,
            lambda = lambda ) ,
        tau = tau ,
        data = na.exclude(
            NSTEMI[
                  ,
                   c(
                       "DaysFromIndexAdmissionToProcedure" ,
                       "Day" )]))


get.qss <- function(model){
    fit <- model$qss$Day$xyz
    fit[,2] <- fit[,2] + model$coef[1]
    return(fit)
}

par( mar = c(5,4,2,4) , las = 1)

 # create a monthly count of NSTEMI
NbyM <- data.frame(
    m = 365/24*( 2*1:24 - 1 ) ,
    n = as.numeric( table( NSTEMI$Month )))

 # rescale the counts to the [0,13] (ylim of main plot)
NbyM$nRescaled <- (NbyM$n)/6


plot(
    0 ,
    xlim = c(0,730) ,
    ylim = c(0,13) ,
    type = "n" ,
    bty = "n" ,
    xlab = "Month of Procedure" ,
    ylab = "Days from Index Admission to Procedure" ,
    main = "" ,
    axes = FALSE)

mtext(
    side = 3 ,
    text = "2013\n(n=768)" ,
    at = 730/4 )

mtext(
    side = 3 ,
    text = "2014\n(n=614)" ,
    at = 730/4*3 )

axis(
    side = 1 ,
    tick = FALSE ,
    at = 365/24*( 2*1:24 - 1 ) ,
    labels = c(1:12,1:12) )

axis(
    side = 2 )

axis(
    side = 4 ,
    col.axis = "blue" ,
    col.ticks = "blue" ,
    col = "blue" ,
    at = (0:7*10)/6 ,
    label = 0:7*10)

segments(
    x0 = 365/12*0:24 ,
    y0 = 0 ,
    x1 = 365/12*0:24 ,
    y1 = 8 ,
    lty = 3 ,
    lwd = 0.8 ,
    col = "#80808080")

abline(
    h = 0:8 ,
    lty = 3 ,
    lwd = 0.8 ,
    col = "#80808080")

abline(
    h = 3 ,
    v = c(0,365,730) ,
    lty = 3 ,
    lwd = 2 ,
    col = "#80808080")


points(
    jitter(DaysFromIndexAdmissionToProcedure) ~ Day ,
    data = NSTEMI ,
    pch = 16 ,
    col = "#A0A0A030")


lines(sm.spline( NbyM$m , NbyM$nRescaled , df = 4) , lwd = 5 , col = "#FFFFFFAA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.75 , lambda = 50)) , df = 18 ) , lwd = 5 , col = "#FFFFFFAA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.50 , lambda = 50)) , df = 18 ) , lwd = 5 , col = "#FFFFFFAA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.25 , lambda = 50)) , df = 18 ) , lwd = 5 , col = "#FFFFFFAA")


lines(sm.spline( NbyM$m , NbyM$nRescaled , df = 4) , lwd = 3 , col = "#A0C0F0AA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.75 , lambda = 30 )) , df = 18 ) , lwd = 3 , col = "#A0A0A0AA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.50 , lambda = 30 )) , df = 18 ) , lwd = 3 , col = "#A0A0A0AA")
lines( sm.spline(get.qss( fit.rqss( tau = 0.25 , lambda = 30 )) , df = 18 ) , lwd = 3 , col = "#A0A0A0AA")

legend(
    x = 400 ,
    y = 13 ,
    bty = "n" ,
    lwd = 5 ,
    col = c("#A0C0F0AA","#A0A0A0AA") ,
    legend = c("Number of NSTEMI per month (right scale)" , "25-, 50-, 75-Percentile (left scale)" ))
```
