---
date: '`r format(Sys.time(), "%d %B, %Y")`'
params:
  title: "Emty tite"
  author: "Anon author"
  hospitalName: "Ukjent sykehus"
  tableFormat: "html"
header-includes:
  - \usepackage[english, norsk]{babel}
  - \usepackage{booktabs}
  - \usepackage{rotating}
title: "`r paste('NORIC', params$hospitalName, 'Stentbruk')`"
author: "`r params$author`"
---

```{r knitrOptions, include=FALSE}
library(magrittr)
library(knitr)
library(kableExtra)

# make sure to use a temporary directory AND absolute paths, e.g. that figs
# can be found also when deployed at a server. See below link for explanation
# https://rgriff23.github.io/2017/04/25/how-to-knit-for-mysite.html
# Also make sure we use tempdir() as working directory so we do not clutter
# the package of the hosting shiny app
#workDir <- tempdir()
#knitr::opts_knit$set(base.dir=workDir, base.url=file.path(paste0(tempdir(), "/")), root.dir = workDir)

# Handle both html and latex (pdf) output. Actually to avoid setting 'format'
# for each kable call
# inspired by https://stackoverflow.com/questions/46080853/why-does-rendering-a-pdf-from-rmarkdown-require-closing-rstudio-between-renders
options(knitr.table.format = params$tableFormat)

knitr::opts_chunk$set(warnings=FALSE,echo=FALSE)
options(stringsAsFactors=FALSE)

# For some reason Shiny Server does not get the server locale settings right.
# To display dates correct, enforce locale here:
Sys.setlocale("LC_TIME", "nb_NO.UTF-8")
``` 


```{r SKDEcol, include=FALSE}

colPrimary <- c("#000059", "#084594", "#2171b5", "#4292c6", "#6baed6", "#c6dbef")
colNeutral <- c("#4D4D4D", "#737373", "#A6A6A6", "#DADADA")
colKontrast <- "#FF7260"

``` 


```{r DefineFunc,include=FALSE}

brew <- function(
    N = 3 ,
    alpha = "AA" ) paste(
        RColorBrewer::brewer.pal(
            n = N , 
            name = if(N<9) "Dark2" else "Set3" ) ,
        alpha ,
        sep = "")

PrettyTabNR <- function( TabN ) {
    TabR <- round(
        100*prop.table(
                TabN ,
                margin = 1 ) ,
        digits = 1 )
    N <- sprintf( "%3.0f" , TabN )
    R <- sprintf( "%4.1f" , TabR )
    T <- paste( R , " (" , N , ")" , sep = "" )
    Tab <- matrix(
        data = T ,
        ncol = ncol(TabN) ,
        byrow = FALSE )
    Tab[ which(Tab==" 0.0 (  0)") ] <- ""
    rownames(Tab) <- rownames(TabN)
    colnames(Tab) <- colnames(TabN)
    return(Tab)
}

PrettyTabN <- function( TabN ) {
    Tab <- sprintf( "%3.0f" , TabN )
    Tab[ which(Tab=="  0") ] <- ""
    return(Tab)
}

PrettyTabR <- function( TabN ) {
    R <- round(
        100*prop.table(
                TabN ,
                margin = 1 ) ,
        digits = 1 )
    R <- sprintf( "%4.1f" , R )
    R[ which( R == " 0.0" ) ] <- ""
    Tab <- matrix(
        data = R ,
        ncol = ncol(TabN) ,
        byrow = FALSE )
    rownames(Tab) <- rownames(TabN)
    colnames(Tab) <- colnames(TabN)
    return(Tab)
}


showN <- 18

``` 

```{r makeStandardTableFunction, eval=TRUE}
mst <- function(tab, type, cap, digs, align = NULL, fs = 8, lsd = FALSE) {
  if (type == "latex") {
    if (lsd) {
      lo <- c("hold_position", "scale_down")
    } else {
      lo <- c("hold_position")
    }
    k <- kable(tab, caption = cap, digits = digs, align = align,
               booktabs = TRUE) %>% 
      kable_styling(latex_options = lo, font_size = fs)
  }
  
  if (type == "html") {
    k <- kable(tab, caption = cap, digits = digs, align = align) %>% 
      kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                    full_width = F)
  }
  print(k)
}
```

```{r GetData,include=FALSE}
baseName <- "noricStaging"

reshID <- rapbase::getShinyUserReshId(session, testCase = TRUE)

registryName <- if (exists( "reshID" )) {
                    noric::NORICmakeRegistryName(
                               baseName = baseName ,
                               reshID = reshID
                           )
                } else {
                    "rapbase"
                }

dbType <- "mysql"

SSQuery <- "SELECT * FROM SegmentStent"
SS <- rapbase::LoadRegData(registryName, SSQuery, dbType)

APQuery <- "
SELECT
   A.ForlopsID ,
   min(A.Sykehusnavn) AS Sykehusnavn ,
   min(A.ProsedyreDato) AS ProsedyreDato ,
   SUM(S.ForlopsID>0) AS Nstents
FROM AngioPCIVar A
LEFT JOIN SegmentStent S
ON A.ForlopsID=S.ForlopsID AND S.StentType <> ''
WHERE A.ProsedyreType  != 'Angio'
GROUP BY ForlopsID;
"

AP <- rapbase::LoadRegData(registryName, APQuery, dbType)


AP$Nstents[ is.na(AP$Nstents) ] <- 0

SS$StentType[SS$StentType==""] <- NA
SS$StentType[SS$StentType=="Annet"] <- "BVS"
SS$StentType <- factor(SS$StentType)

SS$Indikasjon <- car::recode( SS$Indikasjon ,"
   'Stabil koronarsykdom '                    ='SAP';
   'UAP'                                      ='UAP';
   'NSTEMI'                                   ='NSTEMI';
   'STEMI'                                    ='STEMI';
   'STEMI > 24h'                              ='STEMI';
   'STEMI/Rescue PCI'                         ='STEMI';
   ''                                         = NA;
   else                                       ='Annet'
")
 
SS$Indikasjon <- factor( SS$Indikasjon , levels = c(
'SAP',
'UAP',
'NSTEMI',
'STEMI',
'Annet'))


SS$ProsedyreType2 <- car::recode( SS$ProsedyreType , "
    'Direktestent' = 'Stent' ;
    'Ballong + Stent' = 'Stent' ;
    'Medikamentell ballong+ Stent' = 'Stent' ;

    'Ballongdilatasjon' = 'POBA' ;

    'Wireforsøk' = 'Wireforsøk' ;

    'Rotablator' = 'Rotablator' ;

    else = 'Annet'")

SS$ProsedyreDato <- as.Date(
    x = SS$ProsedyreDato ,
    format = "%Y-%m-%d")

SS$Month <- as.numeric(
    format( 
        x = SS$ProsedyreDato , 
        format = "%m" ))

SS$Year <- as.numeric(
    format( 
        x = SS$ProsedyreDato ,
        format = "%y" ))

SS$YearMonth <- factor(
    format(
        x = SS$ProsedyreDato ,
        format = "%y-%m"))



AP$ProsedyreDato <- as.Date(
    x = AP$ProsedyreDato ,
    format = "%Y-%m-%d")
                       
AP$Month <- as.numeric(
    format( 
        x = AP$ProsedyreDato , 
        format = "%m" ))

                         
AP$Year <- as.numeric(
    format( 
        x = AP$ProsedyreDato ,
        format = "%y" ))

AP$YearMonth <- factor(
    format(
        x = AP$ProsedyreDato ,
        format = "%y-%m"))

PCImedStent <- subset(
    AP ,
    Nstents > 0
    )
``` 


# Stent type

## Stent type
  
```{r N_stents_StentType_YearMonth,fig.cap="Antall stenter etter type og måned",fig.width=12,fig.height=8,out.width="\\textwidth"}

op <- par(
    mfcol = c (1,1) ,
    xpd = NA ,
    mar = c(5.1,4.1,4.1,13.1) ,
    bg = "#EEEEEE")

pal <- colPrimary[c(1,3,5)]

barplot(
    xtabs(
        formula = ~ StentType + YearMonth ,
        subset = StentType != "" ,
        data = SS ) , 
    las = 1 ,
    xlab = "Måned" ,
    ylab = "Antall" ,
    col = pal ,
    space = 0.2 ,
    border = FALSE)

legend(
    "right" ,
    inset = -.28 ,
    bty = "n" ,
    horiz = FALSE ,
    fill = pal,
    legend = levels(SS$StentType) ,
    cex = 1)
```



## Stent type


```{r Antall_stenter_etter_type_og_maned,echo=FALSE,results='asis'}
cap <- "Antall stenter etter type og måned"
TabNStentType <- tail(
  xtabs(
    formula = ~ YearMonth + StentType ,
    data = SS ) ,
  n = showN ) %>% 
  addmargins()

mst(TabNStentType, params$tableFormat, cap, 0, align = rep("r", 5))

# print(
#     xtable::xtable(
#         addmargins( TabNStentType ) ,
#         digits = 0 , caption = "Antall stenter etter type og måned") ,
#     booktabs = TRUE ,
#     rotate.colnames = FALSE)

```


## Stent type


```{r Prosent_stenttyper_etter_maned,echo = FALSE , results='asis'}
cap <- "Prosentandel stenter etter typer og måned"
#tab <- addmargins(TabNStentType) %>% 
tab <- prop.table(TabNStentType, margin = 1) * 100

mst(tab, params$tableFormat, cap, 1, align = rep("r", 4))

# print(
#   xtable::xtable(
#     100 * prop.table(
#       addmargins(
#         TabNStentType ,
#         margin = 1
#       ) ,
#       margin = 1
#     ) ,
#     digits = 1 , caption = "Prosentandel stenter etter typer og måned"
#   ) ,
#   booktabs = TRUE ,
#   rotate.colnames = FALSE
# )

```





# Prosedyre type

## Prosedyre type

```{r TabNRProsedyreType,echo=FALSE,results='asis'}
cap <- "Prosent (antall) behandlete segmenter etter prosedyretype og måned"
TabNProsedyreType <- tail(
  xtabs(
    formula = ~ YearMonth + ProsedyreType2 ,
    data = SS
  ) ,
  n = showN+1
)

mst(PrettyTabNR( TabNProsedyreType ), params$tableFormat, cap, 0,
    align = rep("r", 7))
```



# Stenter per prosedyre

## Antall stenter per prosedyre
### `r paste0( range(PCImedStent$ProsedyreDato) , collapse = " til ")`, min. 1 stent (N = `r sum(PCImedStent$Nstents>0)`)

```{r Barplot_Nstent_per_Prosedyre,fig.width=12,fig.height=8}

op <- par(
    mfcol = c (1,1) ,
    xpd = NA ,
    mar = c(5.1,4.1,4.1,13.1) ,
    bg = "#EEEEEE")


TabNStent <- xtabs(
    formula = ~ Nstents ,
    data = PCImedStent )

barplot(
    TabNStent ,
    ylab = "Antall prosedyrer" ,
    border = NA ,
    col = colPrimary[3] )

S <- round( summary(PCImedStent$Nstents) , 1 )

legend(
    "right" ,
    inset = -.28 ,
    bty = "n" ,
    legend = paste(attr(S,"names"), ": " , S , sep = ""))

``` 






# Stent merke

## Stent merke

```{r prepare-data-SS-pci,include=FALSE}

SSpci <- subset(
    SS ,
    ProsedyreType %in% c("Ballong + Stent","Direktestent","Medikamentell ballong+ Stent")
)

# get an overall percentage 
Nname <- sort( table(SSpci$Stentnavn) , decreasing = TRUE ) / length(SSpci$Stentnavn)
# exclude those used in less then 1% of cases
Nname <- Nname[ which(Nname>0.01)]

SSpci$Name3 <- factor(
    x = SSpci$Stentnavn , 
    levels = names(Nname)
    )

``` 



```{r TabNstentNameMonth,echo=FALSE,results='asis'}
cap <- "Antall stenter etter merke og måned"
TabNStentMerke <- tail(
  xtabs(
    formula = ~ YearMonth + Name3 ,
    data = SSpci ) ,
  n = showN )

if (params$tableFormat == "html") {
  kable(TabNStentMerke, caption = cap) %>% 
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                  full_width = F) %>% 
    row_spec(row = 0, font_size = 10, angle = -45)
}

if (params$tableFormat == "latex") {
  print(
    xtable::xtable(
      x = addmargins(TabNStentMerke) ,
      digits = 0 , caption = cap) ,
    booktabs = TRUE ,
    rotate.colnames = TRUE,
    scalebox = 0.8
  )
}

```





```{r TabRstentNameMonth,echo=FALSE,results='asis'}
cap <- "Prosent andel stenter etter merke og måned"

if (params$tableFormat == "html") {
  kable(PrettyTabR(TabNStentMerke), caption = cap) %>% 
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                  full_width = F) %>% 
    row_spec(row = 0, font_size = 10, angle = -45)
}

if (params$tableFormat == "latex") {
  print(
    xtable::xtable(
      x = PrettyTabR( TabNStentMerke ) ,
      digits = 0 , caption = cap) ,
    booktabs = TRUE ,
    rotate.colnames = TRUE,
    scalebox = 0.8)
}

```
