---
title: "`r paste('Norsk register for invasiv kardiologi (NORIC)', 'Månedsrapport: Angiografør/Operatør for ', params$hospitalName ) `"
params:
  author: ukjent forfatter
  hospitalName: ukjent sykehus
  tableFormat: html
  reshID: 999999
  registryName: rapbase
  userFullName: Ukjent bruker
  userRole: ukjent rolle
  rendered_by_shiny: FALSE
header-includes:
- \usepackage[english, norsk]{babel}
- \usepackage{booktabs}
- \usepackage{rotating}
- \usepackage{float}
abstract: '`r paste0("Denne rapporten er generert ved hjelp av resultatløsningen _Rapporteket_ og er kun ment til internt bruk!" , "\\newline ", "\\newline ", "Rapporten inneholder tabeller med resultater basert på forløp registrert ved ", params$hospitalName, ". Opptellinger er gjort per forløp/prosedyre, og ikke per individ. Tabellene presenteres med data fra hele fjoråret samt hittil i år." , "\\newline ", "\\newline ", "Eventuelle spørsmål knyttet til rapporten kan rettes til [noric@helse-bergen.no](mailto:noric@helse-bergen.no)") `'
date: '`r format(Sys.time(), "%d. %B, %Y")`'
registryName: NORIC
regtext: '`r readLines(system.file("registryShortDescription.txt", package = "noric"))`'
reglogo: '`r system.file("logoNORIC.png", package = "noric")`'
userFullName: '`r params$userFullName`'
linkcolor: darkblue
output:
  fig_caption: yes
---

```{r knitrOptions, include=FALSE}
library(magrittr)
library(knitr)
library(kableExtra)
library(dplyr)
library(stringr)
library(janitor)
library(data.table)

# make sure to use a temporary directory AND absolute paths, e.g. that figs
# can be found also when deployed at a server. See below link for explanation
# https://rgriff23.github.io/2017/04/25/how-to-knit-for-mysite.html
# Also make sure we use tempdir() as working directory so we do not clutter
# the package of the hosting shiny app
# workDir <- tempdir()
# knitr::opts_knit$set(base.dir = workDir,
#                      base.url = file.path(paste0(tempdir(), "/")),
#                      root.dir = workDir)

# Handle both html and latex (pdf) output. Actually to avoid setting 'format'
# for each kable call
# inspired by https://stackoverflow.com/questions/46080853/why-does-rendering-a-pdf-from-rmarkdown-require-closing-rstudio-between-renders
options(knitr.table.format = params$tableFormat)

knitr::opts_chunk$set(warnings = FALSE, echo = FALSE)
options(stringsAsFactors = FALSE)

# For some reason Shiny Server does not get the server locale settings right.
# To display dates correct, enforce locale here:
Sys.setlocale("LC_TIME", "nb_NO.UTF-8")
``` 


```{r SKDEcol, include=FALSE}

colPrimary <- c("#000059",
                "#084594",
                "#2171b5",
                "#4292c6",
                "#6baed6",
                "#c6dbef")
colNeutral <- c("#4D4D4D", "#737373", "#A6A6A6", "#DADADA")
colKontrast <- "#FF7260"

``` 

```{r parametre}
showN <- 14
```


```{r latest_entry, include=FALSE, eval=TRUE}
# DATAGRUNNLAG: PERIODE FOR SQL SPØRRING

# NYESTE DATO:
# Finne nyeste prosedyredato (=nyeste registrering). Vi ønsker ikke at
# forhåndsregisrerte planlagte forløp kommer med i rapporten. Derfor brukes
# gårsdagens dato som referanse, ingen forløp etter denne kommer med .
# Vi vil dermed også kunne se dersom ingen nye registreringer gjøres eller om
# overføringer har stoppet opp

# ELDSTE DATO:
# Januar fra i fjor (hele foregående år skal vise i rapporten)



# Nyeste registrering eller gårsdagen (ikke forhåndsregistreringer)
if (params$registryName %in% "noricStagingNasjonal") {
  nyeste_reg <- min(
      (as.Date(Sys.time()) - 1),
      
      noric::getLatestEntryHospital(registryName = params$registryName, 
                                    reshID = params$reshID)
  )
  
} else {
  nyeste_reg <- min(
      (as.Date(Sys.time()) - 1),
      noric::getLatestEntry(registryName = params$registryName)
  )
}



periode_data <- data.frame(nyeste_reg = nyeste_reg) %>% 
    dplyr::mutate(
      
      
      # SISTE DATO AVGJØR SISTE MÅNED: 
      siste_dato_innevarende_mnd = lubridate::ceiling_date(
        x = nyeste_reg, unit =  "month") - lubridate::days(1),
      
      siste_dato = dplyr::case_when(
        # siste dato er nyeste dato --> nyeste mnd er komlett
        siste_dato_innevarende_mnd == nyeste_reg ~ 
          nyeste_reg, 
        
        # siste dato er ikke nyeste --> nyest mnd er ikke komplett, ta forrige
        siste_dato_innevarende_mnd != nyeste_reg ~ 
          lubridate::floor_date(nyeste_reg, "month") - 
          lubridate::days(1), 
        
        TRUE ~ as.Date(NA_character_)),
      
      
      
      
      # SISTE DATO AVGJØR SISTE KVARTAL
      siste_dato_innevarende_kvartal = lubridate::ceiling_date(
        x = nyeste_reg, 
        unit =  "quarter") - lubridate::days(1),
      
      kvartal_komplett_start = dplyr::case_when(
        # siste dato i kvartalet er lik nyeste dato --> kvartalet er komplett
        siste_dato_innevarende_kvartal == nyeste_reg ~ 
          lubridate::floor_date(nyeste_reg, 
                                unit =  "quarter"), 
        
        # siste dato i kvartalet er ulik nyeste dato -->bruk forrige kvartal
        siste_dato_innevarende_kvartal != nyeste_reg ~ 
          lubridate::floor_date(nyeste_reg, 
                                unit =  "quarter") - months(3), 
        
        TRUE ~ as.Date(NA_character_)),
      
      
      
      # Inneværende år: 
      nyesteRegYear = as.numeric(format(siste_dato, format = "%Y")),
      
      # Fjoråret
      sisteHeleYear = nyesteRegYear - 1, 

      # Inneværende måned i år: 
      nyesteRegMnd = as.numeric(format(siste_dato, format = "%m")),
      
      # Første dato for SQL -spørring : 01. januar fjoråret
      forste_dato  = as.Date(paste0(sisteHeleYear, "-01-01"),
                             format = "%Y-%m-%d"), 
      
      # Aortaklaff + Segment stent (indikator per kvartal): 
      forste_dato_kvartal = as.Date(paste0(sisteHeleYear - 1, "-01-01"),
                                  format = "%Y-%m-%d")
    ) %>% 
    dplyr::select(-siste_dato_innevarende_mnd, 
                  -siste_dato_innevarende_kvartal)
  


```


```{r monthTabPrepare, include=FALSE, eval=TRUE}

timeTableMonth <- data.frame(
  monthDato = seq(periode_data$forste_dato, 
                  periode_data$siste_dato,
                  by = "month")) %>% 
  dplyr::transmute(maaned = as.factor(format(x = .data$monthDato, 
                                             format = "%Y-%m"))) %>% 
  dplyr::mutate(maaned = as.ordered(maaned))

timeTableMonth_fjor <- data.frame(
  monthDato = seq(periode_data$forste_dato, 
                  as.Date(paste("30-12-", periode_data$sisteHeleYear), 
                          format = "%d-%m-%Y"),
                  by = "month")) %>% 
  dplyr::transmute(maaned = as.factor(format(x = monthDato, 
                                             format = "%Y-%m"))) %>% 
  dplyr::transmute(
    maaned = as.ordered(maaned))

timeTableMonth_aar <- data.frame(
  monthDato = seq(as.Date(paste("01-01-", periode_data$nyesteRegYear), 
                          format = "%d-%m-%Y"),
                  periode_data$siste_dato,
                  by = "month")) %>% 
  dplyr::transmute(maaned = as.factor(format(x = monthDato, 
                                             format = "%Y-%m"))) %>% 
    dplyr::transmute(
      maaned = as.ordered(maaned))


rangeProsDato <- paste(format(periode_data$forste_dato, 
                              "%d/%m-%Y"), 
                       "til", 
                       format(periode_data$siste_dato, 
                              "%d/%m-%Y"))
```




```{r GetData, include=FALSE, cache=FALSE}

AP <- noric::getPrepApData(registryName = params$registryName,
                           fromDate  = periode_data$forste_dato,
                           toDate = periode_data$siste_dato,
                           singleRow = FALSE)

```

```{r APprepare, include=FALSE, eval=TRUE}
rangeProsDato <- format(range(AP$ProsedyreDato), 
                        format = "%d-%m-%Y")

AP %<>% mutate(
  Angiografor1 = ifelse(is.na(.data$Angiografor1),
                        "Ukjent",
                        .data$Angiografor1),
  
  PCIHovedOperator = ifelse(is.na(.data$PCIHovedOperator),
                            "Ukjent",
                            .data$PCIHovedOperator),
  
  forkortetNavnAngiografor = dplyr::if_else(
    .data$Angiografor1 %in% c("Ukjent"),
    true = .data$Angiografor1,
    false = paste0(
      substr(
        stringr::word(.data$Angiografor1, 1),
        1,
        1),
      ". ",
      stringr::word(.data$Angiografor1, -1)),
    missing = "Missing"),
  
  forkortetNavnPCIoperator = dplyr::if_else(
    .data$PCIHovedOperator %in% c("Ukjent"),
    true = .data$PCIHovedOperator,
    false = paste0(
      substr(
        stringr::word(.data$PCIHovedOperator, 1),
        1,
        1),
      ". ",
      stringr::word(.data$PCIHovedOperator, -1)),
    missing = "Missing")
)


```


`r if(params$tableFormat !="html") {"<!--"}`
# Månedsrapport: Angiografør/Operatør {-}
Denne rapporten er generert ved hjelp av resultatløsningen *Rapporteket* og er 
kun ment til internt bruk!
<br/> <br/>
Rapporten inneholder tabeller med resultater basert på forløp registrert ved 
`r params$hospitalName`. Opptellinger er gjort per forløp/prosedyre, 
og ikke per individ. Tabellene presenteres med data fra perioden 
`r rangeProsDato[1]` til `r rangeProsDato[2]`.
<br/> <br/>
Eventuelle spørsmål knyttet til rapporten kan rettes til [noric@helse-bergen.no](mailto:noric@helse-bergen.no)
`r if(params$tableFormat !="html") {"-->"}`


`r if(params$tableFormat !="latex") {"<!--"}`
\newpage
`r if(params$tableFormat !="latex") {"-->"}`


```{r}
if (params$rendered_by_shiny == TRUE && params$tableFormat == "latex")
    shiny::setProgress(0.35)  # set progress to 35%
```
<br/><br/>

# Angiografør

```{r PrepareDataAngigrafor, include = FALSE}
angiografor_AP <- AP %>% dplyr::filter(
  .data$ProsedyreType %in% c("Angio", "Angio + PCI"))
``` 

```{r TabNAngiogrforMonth, echo = FALSE, results = "asis"}
cap <- paste0("Antall prosedyrer registrert i NORIC hvor det er utført ",
              "koronar angiografi, per måned og navn på angiografør 1. ",
              "Gjelder for ", params$hospitalName, " i perioden ", 
              rangeProsDato[1], " til ", rangeProsDato[2], ". ",
              "Opptellingen er basert på prosedyretypene Angio og Angio+PCI.")

tab_angiografor <- angiografor_AP %>% 
  janitor::tabyl(maaned,
                 forkortetNavnAngiografor,
                 show_missing_levels = FALSE) %>% 
  janitor::adorn_totals("col", name = "Totalt") #%>% 
  # dplyr::rename(" " = "forkortetNavnAngiografor")

TabAngiografor_fjor <- merge(
  x = timeTableMonth_fjor,
  y =  tab_angiografor,
  by.x  = "maaned",
  by.y = "maaned",
  all.x = TRUE) %>%
  janitor::adorn_totals("row", name = paste0("Totalt i ", periode_data$sisteHeleYear)) #%>%
  # dplyr::mutate(aar = periode_data$sisteHeleYear) %>%
  # dplyr::relocate("aar", .before = "maaned")


TabAngiografor_aar <- merge(
  x = timeTableMonth_aar,
  y =  tab_angiografor,
  by.x  = "maaned",
  by.y = "maaned",
  all.x = TRUE) %>%
  janitor::adorn_totals("row", name = paste0("Totalt i ", periode_data$nyesteRegYear)) #%>%
  # dplyr::mutate(aar = periode_data$nyesteRegYear) %>%
  # dplyr::relocate("aar", .before = "maaned")


TabAngiografor <- rbind(
  TabAngiografor_fjor,
  TabAngiografor_aar
)


TabAngiografor[TabAngiografor == 0] <- " - "
TabAngiografor[is.na(TabAngiografor)] <- " - "

t_TabAngiografor <- transpose(TabAngiografor)
rownames(t_TabAngiografor) <- colnames(TabAngiografor) 
colnames(t_TabAngiografor) <- rep("", ncol(t_TabAngiografor))

# align <- c("l", rep("c", dim(t_TabAngiografor)[2] - 1))

# if (params$tableFormat == "html") {
#   t_TabAngiografor %>% #dplyr::select(-aar) %>% rename(" " = "maaned") %>%
#     knitr::kable(caption = cap, align = align) %>%
#     kableExtra::kable_styling(bootstrap_options = c("striped",
#                                                     "hover",
#                                                     "condensed"),
#                               full_width = FALSE,
#                               font_size = 11) %>%
#     # kableExtra::row_spec(row = 1, width = "7em") %>%
#     # kableExtra::column_spec(column = 0, font_size = 10, angle = -45) %>%
#     kableExtra::column_spec(column = 12, border_right =  TRUE) %>%
#     kableExtra::column_spec(column = 13, border_right =  TRUE) %>%
#     kableExtra::column_spec(column = dim(t_TabAngiografor)[1]-1, border_right =  TRUE) #%>% 
#   # add_header_above(c(as.character(periode_data$sisteHeleYear) = 12,
#   #                    as.character(periode_data$nyesteRegYear) =dim(t_TabAngiografor)[1,]))
# } else if (params$tableFormat == "latex") {
#   t_TabAngiografor %>% dplyr::select(-aar) %>% rename(" " = "maaned") %>%
#     knitr::kable(format = params$tableFormat,
#                caption = cap,
#                booktabs = TRUE,
#                align = "r") %>%
#     kableExtra::kable_styling(latex_options = "HOLD_position",
#                              font_size = 10) %>%
#    kableExtra::row_spec(row = 0, angle = 90) %>%
#     kableExtra::row_spec(row=12, hline_after =  TRUE) %>%
#     kableExtra::row_spec(row=13, hline_after =  TRUE)%>%
#     kableExtra::row_spec(row=dim(t_TabAngiografor)[1]-1, hline_after =  TRUE) %>%
#     kableExtra::pack_rows(group_label = as.character(periode_data$sisteHeleYear),
#                           start_row = 1,
#                           end_row = 13) %>%
#     kableExtra::pack_rows(group_label = as.character(periode_data$nyesteRegYear),
#                           start_row = 14,
#                           end_row = dim(t_TabAngiografor)[1])
# }

t_TabAngiografor[t_TabAngiografor == 0] <- " - "
t_TabAngiografor[is.na(t_TabAngiografor)] <- " - "

align <- c("l", rep("c", dim(t_TabAngiografor)[2] - 1))

if (params$tableFormat == "html") {
  t_TabAngiografor %>%
    knitr::kable(caption = cap,
               align = align) %>%
    kableExtra::kable_styling(bootstrap_options = c("striped",
                                                    "hover",
                                                    "condensed"),
                              full_width = FALSE) %>%
    kableExtra::row_spec(row = 1, font_size = 10, bold = TRUE,angle = -45) %>%
    kableExtra::column_spec(column = 1, width = "7em") %>% 
    kableExtra::column_spec(column = 12, border_left =  TRUE, border_right = TRUE) %>% 
    kableExtra::column_spec(column = ncol(t_TabAngiografor), border_left =  TRUE, border_right = TRUE)
  
} else if (params$tableFormat == "latex") {
  t_TabAngiografor %>%
  knitr::kable(format = params$tableFormat,
               caption = cap,
               booktabs = TRUE,
               align = align) %>%
    kableExtra::kable_styling(latex_options = c("HOLD_position",
                                                "scale_down")) %>%
    kableExtra::row_spec(row = 0, angle = 90)
}
```

```{r}
if (params$rendered_by_shiny == TRUE && params$tableFormat == "latex")
    shiny::setProgress(0.7)  # set progress to 70%
```


`r if(params$tableFormat !="latex") {"<!--"}`
\newpage
`r if(params$tableFormat !="latex") {"-->"}`

<br/><br/>

# PCI-operatør

```{r PrepareDataOperator, include = FALSE}
pciOperator_AP <- AP %>% dplyr::filter(
  .data$ProsedyreType %in% c("Angio + PCI", "PCI"))
``` 

```{r TabNOperatorMonth, echo = FALSE, results = "asis"}
cap <- paste0("Antall prosedyrer registrert i NORIC hvor det er utført PCI, ",
              "per måned og navn på hovedoperatør. ",
              "Gjelder for ", params$hospitalName, " i perioden ",
              rangeProsDato[1], " til ", rangeProsDato[2], ". ",
              "Opptellingen er basert på prosedyretypene Angio+PCI og PCI.")


tab_pciOperator <- pciOperator_AP %>%
  janitor::tabyl(forkortetNavnPCIoperator,
                 maaned,
                 show_missing_levels = FALSE) %>%
  janitor::adorn_totals("col", name = "Totalt") %>%
  dplyr::rename(" " = "forkortetNavnPCIoperator")


# TabPCIOperator_fjor <- merge(
#   x = timeTableMonth_fjor,
#   y =  tab_pciOperator,
#   by.x  = "maaned", 
#   by.y = "maaned", 
#   all.x = TRUE) %>% 
#   janitor::adorn_totals("row", name = paste0("Totalt i ", periode_data$sisteHeleYear)) %>% 
#   dplyr::mutate(aar = periode_data$sisteHeleYear) %>% 
#   dplyr::relocate("aar", .before = "maaned")
# 
# 
# TabPCIOperator_aar <- merge(
#   x = timeTableMonth_aar,
#   y =  tab_pciOperator,
#   by.x  = "maaned", 
#   by.y = "maaned", 
#   all.x = TRUE) %>% 
#   janitor::adorn_totals("row", name = paste0("Totalt i ", periode_data$nyesteRegYear)) %>% 
#   dplyr::mutate(aar = periode_data$sisteHeleYear) %>% 
#   dplyr::relocate("aar", .before = "maaned")
# 
# 
# TabPCIOperator <- rbind(
#   TabPCIOperator_fjor, 
#   TabPCIOperator_aar
# )
# 
# 
# TabPCIOperator[TabPCIOperator == 0] <- " - "
# TabPCIOperator[is.na(TabPCIOperator)] <- " - "
# 
# align <- c("l", rep("c", dim(TabPCIOperator)[2] - 1))
# 
# if (params$tableFormat == "html") {
#   TabPCIOperator %>% dplyr::select(-aar) %>% rename(" " = "maaned") %>% 
#     knitr::kable(caption = cap, align = align) %>%
#     kableExtra::kable_styling(bootstrap_options = c("striped",
#                                                     "hover",
#                                                     "condensed"),
#                               full_width = FALSE, 
#                               font_size = 11) %>%
#     kableExtra::column_spec(column = 1, width = "7em") %>%
#     kableExtra::row_spec(row = 0, font_size = 10, angle = -45) %>%
#     kableExtra::row_spec(row=12, hline_after =  TRUE) %>%
#     kableExtra::row_spec(row=13, hline_after =  TRUE) %>%
#     kableExtra::row_spec(row=dim(TabPCIOperator)[1]-1, hline_after =  TRUE) %>%
#     kableExtra::pack_rows(group_label = as.character(periode_data$sisteHeleYear),
#                           start_row = 1, 
#                           end_row = 13) %>% 
#     kableExtra::pack_rows(group_label = as.character(periode_data$nyesteRegYear),
#                           start_row = 14, 
#                           end_row = dim(TabPCIOperator)[1])
# 
# } else if (params$tableFormat == "latex") {
#   TabPCIOperator %>% dplyr::select(-aar) %>% rename(" " = "maaned") %>% 
#     knitr::kable(format = params$tableFormat,
#                caption = cap,
#                booktabs = TRUE,
#                align = "r") %>%
#     kableExtra::kable_styling(latex_options = "HOLD_position", 
#                              font_size = 10) %>%
#    kableExtra::row_spec(row = 0, angle = 90) %>%
#     kableExtra::row_spec(row=12, hline_after =  TRUE) %>%
#     kableExtra::row_spec(row=13, hline_after =  TRUE)%>%
#     kableExtra::row_spec(row=dim(TabPCIOperator)[1]-1, hline_after =  TRUE) %>%
#     kableExtra::pack_rows(group_label = as.character(periode_data$sisteHeleYear),
#                           start_row = 1,
#                           end_row = 13) %>% 
#     kableExtra::pack_rows(group_label = as.character(periode_data$nyesteRegYear),
#                           start_row = 14, 
#                           end_row = dim(TabPCIOperator)[1])
# }



tab_pciOperator[tab_pciOperator == 0] <- " - "
tab_pciOperator[is.na(tab_pciOperator)] <- " - "

align <- c("l", rep("c", dim(tab_pciOperator)[2] - 1))

if (params$tableFormat == "html") {
  tab_pciOperator %>%
    knitr::kable(caption = cap,
               align = align) %>%
    kableExtra::kable_styling(bootstrap_options = c("striped",
                                                    "hover",
                                                    "condensed"),
                              full_width = FALSE) %>%
    kableExtra::row_spec(row = 0, font_size = 10, angle = -45) %>%
    kableExtra::column_spec(column = 1, width = "7em")
} else if (params$tableFormat == "latex") {
  tab_pciOperator %>%
  knitr::kable(format = params$tableFormat,
               caption = cap,
               booktabs = TRUE,
               align = align) %>%
    kableExtra::kable_styling(latex_options = c("HOLD_position",
                                                "scale_down")) %>%
    kableExtra::row_spec(row = 0, angle = 90)
}
```

```{r}
if (params$rendered_by_shiny == TRUE && params$tableFormat == "latex")
    shiny::setProgress(1)  # set progress to 100%
```
