SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `AndreProsedyrerVar`;
CREATE TABLE `AndreProsedyrerVar` (
  `ForlopsID` int(9) NOT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Regtype` varchar(8) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `ProsedyreTid` time DEFAULT NULL,
  `ProsedyreTidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenProsType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndreProsOperatorer` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Komplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LettAllergi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ModeratAllergi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Arytmi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HemodynKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NeuroKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VaskulKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Perforasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AkuttACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAlvorligKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsRelatertDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatus` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_AndreProsedyrerVar` (`AvdRESH`,`ProsedyreDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `AngioPCI`;
CREATE TABLE `AngioPCI` (
  `LabNummer` tinyint(3) DEFAULT NULL,
  `ForlopsID` bigint(19) NOT NULL DEFAULT '0',
  `PasientID` bigint(19) NOT NULL DEFAULT '0',
  `PrimaerForlopsID` bigint(19) DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `ProsedyreType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HendelsesType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kjonn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `PasientRegDato` date DEFAULT NULL,
  `SymptomDato` date DEFAULT NULL,
  `SymptomTidspunkt` time DEFAULT NULL,
  `BesUtlEKGDato` date DEFAULT NULL,
  `BesUtlEKGTid` time DEFAULT NULL,
  `Vakttid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(5) DEFAULT NULL,
  `Vekt` smallint(5) DEFAULT NULL,
  `SKreatinin` smallint(5) DEFAULT NULL,
  `TidlPCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlABC` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RoykeStatus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehHypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LipidSenkende` bit(1) DEFAULT NULL,
  `TidlInfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KjentNedsattVenstVentr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diabetes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Insulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferKarsykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StegvisProsedyre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CanadianClass` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KardiogentSjokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KillipKlasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Funn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnkomstPCIDato` date DEFAULT NULL,
  `AnkomstPCITid` time DEFAULT NULL,
  `Stikksted` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseTidlBehSegment` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseACBGraft` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stresskardiomyopati` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PrimarBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BareDiag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FFR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Doppler` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenDiag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `IVUS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OCT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AdjuvantTerapi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aortaballongpumpe` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MekKompr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAdj` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenVenstreKammerAssist` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoForApningKar` date DEFAULT NULL,
  `TidsPunktForApningKar` time DEFAULT NULL,
  `UkjentTidsPunktForApningKar` tinyint(3) DEFAULT NULL,
  `KarAapentVedAngio` tinyint(3) DEFAULT NULL,
  `KarIkkeAapnet` tinyint(3) DEFAULT NULL,
  `Straledose` bigint(19) DEFAULT NULL,
  `GjenLysTidSek` int(10) DEFAULT NULL,
  `Kontrastmiddel` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KontrastMengdeMl` smallint(5) DEFAULT NULL,
  `AnnKonMidUndersokelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ArteriellLukning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabAllergiskLettModerat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabAllergiskAlvorlig` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehandlingskrevendeArytmi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HemodynamiskKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabNeurologiskKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VaskulaerIkkeKoronar` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MistetStent` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VedvarendeSidegrensokklusjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Perforasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AkuttACBOperasjonFraLab` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LAbAnnenAlvorligKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabProsedyrerelatertDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngioOperatorer` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnleggelsesdatoDetteSykehus` bit(1) DEFAULT NULL,
  `OverflyttetFra` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OverflyttetFraSykehus` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoInnleggelseIHenvisendeSykehus` date DEFAULT NULL,
  `EKGRytme` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EKGQRS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VenstreGrenblokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EKGSTT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BeslutningsutlosendeEKG` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjertefrekvens` smallint(5) DEFAULT NULL,
  `SystoliskBlodtrykk` smallint(5) DEFAULT NULL,
  `DiastoliskBlodtrykk` smallint(5) DEFAULT NULL,
  `KardiogentSjokkVedAnkomst` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Innkomstarsak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HLRForSykehus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `GittTrombolyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseMedikament` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseTidspunkt` date DEFAULT NULL,
  `AngiTidpunktDaTrombolysebehandlingenBlePabegynt` time DEFAULT NULL,
  `TidligereHjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligerePCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereACBOperasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenTidligereHjertekirurgiIkkePacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereHjerneslagIkkeTIA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SGlukose` decimal(4,2) DEFAULT NULL,
  `Infarktmarkoer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktMarkoerMax` decimal(8,3) DEFAULT NULL,
  `Kolesterol` decimal(4,2) DEFAULT NULL,
  `CRP` decimal(5,1) DEFAULT NULL,
  `HbA1c` decimal(4,1) DEFAULT NULL,
  `HDL` decimal(3,2) DEFAULT NULL,
  `Hemoglobin` decimal(3,1) DEFAULT NULL,
  `MaaltLDL` decimal(4,2) DEFAULT NULL,
  `Kreatinin` int(10) DEFAULT NULL,
  `Triglycerider` decimal(4,2) DEFAULT NULL,
  `SEGMENT1` tinyint(3) DEFAULT NULL,
  `SEGMENT2` tinyint(3) DEFAULT NULL,
  `SEGMENT3` tinyint(3) DEFAULT NULL,
  `SEGMENT4` tinyint(3) DEFAULT NULL,
  `SEGMENT5` tinyint(3) DEFAULT NULL,
  `SEGMENT6` tinyint(3) DEFAULT NULL,
  `SEGMENT7` tinyint(3) DEFAULT NULL,
  `SEGMENT8` tinyint(3) DEFAULT NULL,
  `SEGMENT9` tinyint(3) DEFAULT NULL,
  `SEGMENT10` tinyint(3) DEFAULT NULL,
  `SEGMENT11` tinyint(3) DEFAULT NULL,
  `SEGMENT12` tinyint(3) DEFAULT NULL,
  `SEGMENT13` tinyint(3) DEFAULT NULL,
  `SEGMENT14` tinyint(3) DEFAULT NULL,
  `SEGMENT15` tinyint(3) DEFAULT NULL,
  `SEGMENT16` tinyint(3) DEFAULT NULL,
  `SEGMENT17` tinyint(3) DEFAULT NULL,
  `SEGMENT18` tinyint(3) DEFAULT NULL,
  `SEGMENT19` tinyint(3) DEFAULT NULL,
  `SEGMENT20` tinyint(3) DEFAULT NULL,
  `Myokardskademarkor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `STSegmentSenkning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SekundaerBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DistalProtectionDevice` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Trombectomy` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `GenereltSuksess` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KomplettRevaskularisering` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PCIOperatorer` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Komplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AllergiskSenkomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NoenFormForBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BlodningMajor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BlodningMinor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehandlingskrevendePseudoaneurysme` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HematomFemCmDiam` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HbFall` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlengetKompresjonstid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlengetOpphold` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UltralydsundersokelseCT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Blodtransfusjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KirurgiskBehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenBehandlingUtoverKompresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidUtsettAvAntitrombotiskBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdVaskulaerIkkeKoronar` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdNeurologiskKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NytilkommetNyreinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KomplikasjonRePCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ACBOperasjonKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdAnnenAlvorligKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdelingsDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdelingsProsedyrerelatertDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ACEHemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `A2Blokkerre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Antikoagulantia` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ASA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndrePlatehemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Betablokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CaBlokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiabetesBehandlingInsulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiabetesBehandlingPerOral` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Digitalis` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diuretika` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aldosteronantagonister` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Statiner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OvrigeLipidsenkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NitroglycerinLangtidsvirkende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrevetDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrevetDodsdato` date DEFAULT NULL,
  `AnnenAlvorligSykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infarkttype` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SubklassifiseringAvHjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Utskrivningsdato` date DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci NOT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci NOT NULL,
  PRIMARY KEY (`ForlopsID`,`AvdRESH`),
  KEY `ForlopsID` (`ForlopsID`,`AvdRESH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `AngioPCIVar`;
CREATE TABLE `AngioPCIVar` (
  `ForlopsID` int(9) NOT NULL,
  `PrimaerForlopsID` int(10) unsigned DEFAULT NULL,
  `PasientID` int(10) unsigned DEFAULT NULL,
  `Regtype` varchar(8) COLLATE utf8_danish_ci DEFAULT NULL,
  `Lokalsykehus` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `ProsedyreTid` time DEFAULT NULL,
  `ProsedyreTidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hastegrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kjonn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `PasientRegDato` date DEFAULT NULL,
  `Studie` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `SymptomDato` date DEFAULT NULL,
  `SymptomTid` time DEFAULT NULL,
  `BesUtlEKGDato` date DEFAULT NULL,
  `BesUtlEKGTid` time DEFAULT NULL,
  `BesUtlEKGTidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vakttid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `SKreatinin` smallint(6) DEFAULT NULL,
  `TidlPCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlABC` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RoykeStatus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehHypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Statiner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlInfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KjentNedsattVenstVentr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diabetes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Insulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereSlag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferKarsykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Myokardskademarkor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `STSegmentSenkning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StegvisProsedyre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CanadianClass` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KardiogentSjokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KillipKlasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Funn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnkomstPCIDato` date DEFAULT NULL,
  `AnkomstPCITid` time DEFAULT NULL,
  `AnkomstPCITidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stikksted` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseTidlBehSegment` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseACBGraft` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stresskardiomyopati` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PrimarBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BareDiag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FFR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Doppler` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `IVUS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OCT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `IFR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NIRS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenDiag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tilleggsprosedyrer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HoyreHjerteKat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ventilfilming` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Perikardiocentese` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AdjuvantTerapi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aortaballongpumpe` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Impella` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ECMO` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenVenstreKammerAssist` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MekKompr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DistalProtectionDevice` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Trombectomy` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PTAHalskar` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PTSMA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAdj` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ApningKarDato` date DEFAULT NULL,
  `ApningKarTid` time DEFAULT NULL,
  `ApningKarTidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KarAapentVedAngio` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KarIkkeAapnet` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `GenereltSuksess` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabNummer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Straledose` bigint(20) DEFAULT NULL,
  `GjenLysTidSek` int(11) DEFAULT NULL,
  `Kontrastmiddel` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KontrastMengdeMl` smallint(6) DEFAULT NULL,
  `AnnKonMidUndersokelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ArteriellLukning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAllergiskLettModerat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAllergiskAlvorlig` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompBehkrevendeArytmi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompHemodynamisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompNeurologisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompVaskulaerIkkeKoronar` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompMistetStent` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompVedvarSidegrensokkl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompPerforasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAkuttACBOperasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAnnenAlv` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompProsedyrerelatertDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OverflyttetFra` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OverflyttetFraSykehus` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnleggelseHenvisendeSykehusDato` date DEFAULT NULL,
  `InnleggelseHenvisendeSykehusDatoUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnleggelseHenvisendeSykehusTid` time DEFAULT NULL,
  `InnleggelseHenvisendeSykehusTidUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Innkomstarsak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SymptomdebutDato` date DEFAULT NULL,
  `SymptomdebutTid` time DEFAULT NULL,
  `HLRForSykehus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EKGRytme` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EKGQRS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EKGSTT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VenstreGrenblokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BeslutningsutlosendeEKG` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BeslEKGDato` date DEFAULT NULL,
  `BeslEKGTid` time DEFAULT NULL,
  `BeslEKGUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjertefrekvens` smallint(6) DEFAULT NULL,
  `SystoliskBlodtrykk` smallint(6) DEFAULT NULL,
  `DiastoliskBlodtrykk` smallint(6) DEFAULT NULL,
  `KillipKlasseAnkomst` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KardiogentSjokkAnkomst` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `GittTrombolyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseMedikament` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseDato` date DEFAULT NULL,
  `TrombolyseTid` time DEFAULT NULL,
  `TrombolyseUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereACBOp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenTidlKirurgi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitASA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitAntikoagulantia` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitAndrePlatehemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitStatiner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitNSAID` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitACEHemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitA2Blokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitBetaBlokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitCaHemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitDiabetesPrOral` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitDigitalis` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitDiuretika` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitAldosteronantagonist` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitOvrigLipid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InitNitroglycerin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infarktmarkoer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktMarkoerMax` decimal(8,3) DEFAULT NULL,
  `Kolesterol` decimal(4,2) DEFAULT NULL,
  `Triglycerider` decimal(4,2) DEFAULT NULL,
  `HDL` decimal(3,2) DEFAULT NULL,
  `MaaltLDL` decimal(4,2) DEFAULT NULL,
  `SGlukose` decimal(4,2) DEFAULT NULL,
  `HbA1c` decimal(4,1) DEFAULT NULL,
  `Kreatinin` mediumint(9) DEFAULT NULL,
  `CRP` decimal(5,1) DEFAULT NULL,
  `Hemoglobin` decimal(3,1) DEFAULT NULL,
  `SEGMENT1` tinyint(3) DEFAULT NULL,
  `SEGMENT2` tinyint(3) DEFAULT NULL,
  `SEGMENT3` tinyint(3) DEFAULT NULL,
  `SEGMENT4` tinyint(3) DEFAULT NULL,
  `SEGMENT5` tinyint(3) DEFAULT NULL,
  `SEGMENT6` tinyint(3) DEFAULT NULL,
  `SEGMENT7` tinyint(3) DEFAULT NULL,
  `SEGMENT8` tinyint(3) DEFAULT NULL,
  `SEGMENT9` tinyint(3) DEFAULT NULL,
  `SEGMENT10` tinyint(3) DEFAULT NULL,
  `SEGMENT11` tinyint(3) DEFAULT NULL,
  `SEGMENT12` tinyint(3) DEFAULT NULL,
  `SEGMENT13` tinyint(3) DEFAULT NULL,
  `SEGMENT14` tinyint(3) DEFAULT NULL,
  `SEGMENT15` tinyint(3) DEFAULT NULL,
  `SEGMENT16` tinyint(3) DEFAULT NULL,
  `SEGMENT17` tinyint(3) DEFAULT NULL,
  `SEGMENT18` tinyint(3) DEFAULT NULL,
  `SEGMENT19` tinyint(3) DEFAULT NULL,
  `SEGMENT20` tinyint(3) DEFAULT NULL,
  `SEGMENT1VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT2VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT3VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT4VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT5VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT6VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT7VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT8VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT9VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT10VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT11VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT12VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT13VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT14VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT15VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT16VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT17VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT18VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT19VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT20VeneStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT1ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT2ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT3ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT4ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT5ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT6ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT7ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT8ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT9ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT10ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT11ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT12ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT13ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT14ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT15ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT16ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT17ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT18ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT19ArterieStenosgrad` int(11) DEFAULT NULL,
  `SEGMENT20ArterieStenosgrad` int(11) DEFAULT NULL,
  `SekundaerBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KomplettRevaskularisering` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntitrombotiskFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ASAFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ClopidogrelFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PrasugrelFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TicagrelorFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HeparinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DalteparinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EnoxaparinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnetLavmolHeparinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BivalirudinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FondaparinuxFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AbciximabFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EptifibatidFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TirofibanFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `WarfarinFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DabigatranFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ApiksabanFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RivaroksabanFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EdoksabanFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KangrelorFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnetAntitrombotiskFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntitrombotiskUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TrombolyseUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ASAUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ClopidogrelUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PrasugrelUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TicagrelorUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HeparinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DalteparinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EnoxaparinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnetLavmolHeparinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BivalirudinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FondaparinuxUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AbciximabUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EptifibatidUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TirofibanUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `WarfarinUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KangrelorUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnetAntitrombotiskUnder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PCIHovedOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `PCIAndreOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `PCITredjeOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor1` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor2` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor3` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `PCIOperatorer` varchar(300) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngioOperatorer` varchar(300) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAllergisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodningMajor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodningMinor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompPseudoaneurysme` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHematomStor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHbFallStor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompForlengetTidStor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompForlengetOppholdStor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompUltralydCT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodtransfusjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompKirurgiskBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAnnenBehUtoverKompresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTidligUtsettelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompVaskulaer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompNeurologiskKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompNyNyreinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompPCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAnnenAlvorlig` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompProsedyrerelatertDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CKMBFor` mediumint(9) DEFAULT NULL,
  `CKMBEtter` mediumint(9) DEFAULT NULL,
  `TroponinMetFor` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TroponinVerdiFor` int(11) DEFAULT NULL,
  `TroponinMetEtter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TroponinVerdiEtter` int(11) DEFAULT NULL,
  `Utskrivningsdato` date DEFAULT NULL,
  `UtskrevetDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrevetDodsdato` date DEFAULT NULL,
  `ASA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Antikoagulantia` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndrePlatehemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrStatiner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NSAID` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ACEHemmere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `A2Blokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Betablokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CaBlokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiabetesBehandlingInsulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiabetesBehandlingPerOral` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Digitalis` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diuretika` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aldosteronantagonister` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OvrigeLipidsenkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NitroglycerinLangtid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAlvorligSykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktSubklasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrDiagnoser` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatusStart` tinyint(3) DEFAULT NULL,
  `SkjemastatusHovedskjema` tinyint(3) DEFAULT NULL,
  `SkjemaStatusUtskrivelse` tinyint(3) DEFAULT NULL,
  `SkjemaStatusKomplikasjoner` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_AngioPCIVar` (`AvdRESH`,`ProsedyreDato`,`ProsedyreType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `AnnenDiagnostikkVar`;
CREATE TABLE `AnnenDiagnostikkVar` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientKjonn` varchar(13) COLLATE utf8_danish_ci DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `Regtype` varchar(8) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor1` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor2` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor3` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `segment` varchar(100) COLLATE utf8_danish_ci NOT NULL,
  `graft` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `metode` varchar(100) COLLATE utf8_danish_ci NOT NULL,
  `FfrFoer` decimal(5,2) DEFAULT NULL,
  `FfrEtter` decimal(5,2) DEFAULT NULL,
  `IfrFoer` decimal(5,2) DEFAULT NULL,
  `IfrEtter` decimal(5,2) DEFAULT NULL,
  `CsaFoer` decimal(5,1) DEFAULT NULL,
  `CsaEtter` decimal(5,1) DEFAULT NULL,
  `MldFoer` decimal(5,1) DEFAULT NULL,
  `MldEtter` decimal(5,1) DEFAULT NULL,
  `MlaFoer` decimal(5,2) DEFAULT NULL,
  `MlaEtter` decimal(5,2) DEFAULT NULL,
  `MxlcbiFoer` int(10) unsigned DEFAULT NULL,
  `MxlcbiEtter` int(10) unsigned DEFAULT NULL,
  `CfrFoer` tinyint(3) unsigned DEFAULT NULL,
  `CfrEtter` tinyint(3) unsigned DEFAULT NULL,
  `ImrFoer` tinyint(3) unsigned DEFAULT NULL,
  `ImrAfter` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`,`segment`,`metode`),
  KEY `idx_AnnenDiagnostikkVar` (`AvdRESH`,`ProsedyreDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `AortaklaffOppfVar`;
CREATE TABLE `AortaklaffOppfVar` (
  `ForlopsID` int(9) NOT NULL,
  `BasisForlopsID` int(10) unsigned DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BasisScreeningBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BasisBeslutningsDato` date DEFAULT NULL,
  `BasisProsedyreDato` date DEFAULT NULL,
  `OppfDato` date DEFAULT NULL,
  `OppfType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfAvdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfAvdodDato` date DEFAULT NULL,
  `OppfDodProsRelatert` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `HoydeUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `VektUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CanadianClass` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gangtest` smallint(6) DEFAULT NULL,
  `GangtestIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SKreatinin` mediumint(9) DEFAULT NULL,
  `SKreatininIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProBNP` mediumint(9) DEFAULT NULL,
  `Hemoglobin` decimal(3,1) DEFAULT NULL,
  `HemoglobinUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MaxGradient` smallint(6) DEFAULT NULL,
  `MaxGradientMPS` decimal(2,1) DEFAULT NULL,
  `Middelgradient` smallint(6) DEFAULT NULL,
  `VenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PulmonalHypertensjon` tinyint(3) DEFAULT NULL,
  `Aortainsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ParavalvularLekkasje` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mitralinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hygiene` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aktiviteter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SmerterUbehag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngstDepresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Helsetilstand` smallint(6) DEFAULT NULL,
  `Komplikasjoner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Endokarditt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dialyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProteseDysfunk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SenKarKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatus` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_AortaklaffOppfVar` (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `AortaklaffVar`;
CREATE TABLE `AortaklaffVar` (
  `ForlopsID` int(9) NOT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `ScreeningBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BeslutningsDato` date DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `AkuttOperasjon` tinyint(3) DEFAULT NULL,
  `Studie` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `HoydeUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `VektUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Royker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SKreatininFoer` smallint(6) DEFAULT NULL,
  `SKreatininIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProBNPFoer` mediumint(9) DEFAULT NULL,
  `HemoglobinFoer` decimal(3,1) DEFAULT NULL,
  `BehHypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diabetes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Insulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Atrieflimmer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktSiste90d` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlHjerteoperasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlAVR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlMitralplastikk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlMVR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlAnnet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlPCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlHjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KOLS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferKarsykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAlvorligSykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHAKlasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CanadianClass` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Frailty` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RedusertMobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gangtest` smallint(6) DEFAULT NULL,
  `GangtestIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gripestyrke` smallint(6) DEFAULT NULL,
  `DialyseFoerOp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KritiskPreopTilstand` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hastegrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaRisiko` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaRisikoAlder` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaRisikoSpiro` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaRisikoACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaRisikoSpesiell` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Porselenaorta` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Malignitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UgunstigAnatomi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Steroidbehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stralebehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Thoraxdeformitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenAlvorligSykdomKirRisiko` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PerkKlaffPgaPasient` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hygiene` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aktiviteter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SmerterUbehag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngstDepresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Helsetilstand` smallint(6) DEFAULT NULL,
  `Klaffeareal` decimal(3,2) DEFAULT NULL,
  `KlaffearealIkkeBeregnet` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KorrigertKlaffeareal` decimal(3,2) DEFAULT NULL,
  `PreMaxgradient` smallint(6) DEFAULT NULL,
  `PreMaxHastighet` decimal(3,2) DEFAULT NULL,
  `PreMaxHastMangler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreMiddelgradient` smallint(6) DEFAULT NULL,
  `PreVenstreVentrikkelFunksjon2011` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreVenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PulmonalHypertensjon` tinyint(3) DEFAULT NULL,
  `PreAortainsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreMitralisinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErCTForetatt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnulusdiameterVedCT` tinyint(3) DEFAULT NULL,
  `AnnulusAreal` decimal(3,2) DEFAULT NULL,
  `AnnulusPerimeter` decimal(4,2) DEFAULT NULL,
  `Aortaforkalk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TypeKlaff` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `STSScore` tinyint(3) DEFAULT NULL,
  `HovedOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndreOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `TredjeOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Operatorer` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Punksjonstid` time DEFAULT NULL,
  `Avslutningstid` time DEFAULT NULL,
  `Mitralisinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OperativTilgang` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KlaffIKlaff` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TypeKlaffeprotese` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProteseStr` tinyint(3) DEFAULT NULL,
  `Predilatasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PredilBallongStr` tinyint(3) DEFAULT NULL,
  `Postdilatasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostdilBallongStr` tinyint(3) DEFAULT NULL,
  `ProtectionDevice` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Karlukning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RapidPacing` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Anestesi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VellykketProsedyre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Labnr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Straaledose` decimal(8,2) DEFAULT NULL,
  `GjennomLysTid` int(11) DEFAULT NULL,
  `Kontrastmiddel` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kontrastmengde` smallint(6) DEFAULT NULL,
  `LabKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompArytmi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompNeurologi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAkuttKlaff` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAkuttVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompOkklusjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAnestesi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompHLMaskin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompProtese` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompEmboli` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dodsdato` date DEFAULT NULL,
  `AvdKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerneslagGrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTIA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompPacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAtrieflimmer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodningGrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompInfeksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompDialyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostUndersokelseForetatt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMaxgradient` smallint(6) DEFAULT NULL,
  `PostMaxHastighet` decimal(2,1) DEFAULT NULL,
  `PostMiddelgradient` smallint(6) DEFAULT NULL,
  `PostVenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostPulmonalHypertensjon` tinyint(3) DEFAULT NULL,
  `PostAortainsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ParavalvularLekkasje` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMitralisinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrKreatinin` smallint(6) DEFAULT NULL,
  `UtskrKreatininIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrDato` date DEFAULT NULL,
  `UtskrevetTil` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ASAVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntikoagulantiaVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndrePlatehemmereVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatus` int(11) DEFAULT NULL,
  `SkjemaStatusHovedskjema` tinyint(3) DEFAULT NULL,
  `SkjemaStatusKomplUtsk` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_AortaklaffVar` (`AvdRESH`,`ProsedyreDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `CTAngioVar`;
CREATE TABLE `CTAngioVar` (
  `ForlopsID` int(9) NOT NULL,
  `PasientID` int(10) unsigned DEFAULT NULL,
  `Lokalsykehus` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kjonn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `PasientRegDato` date DEFAULT NULL,
  `Studie` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UndersokDato` date DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `SKreatinin` smallint(6) DEFAULT NULL,
  `TidligerePCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diabetes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Insulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RoykingFoer2009` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Royking` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Lipidsenkende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereInfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Granskere` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ViktigsteSymptomer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SluttForKontrast` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HoyCalciumScore` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SluttForKontrastAndreGrunner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseOkklusjonABC` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CalciumScore` smallint(6) DEFAULT NULL,
  `KoronarundersokelseUtfort` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Konklusiv` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseOkklusjonTidligere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Funn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FunnConcat` varchar(400) COLLATE utf8_danish_ci DEFAULT NULL,
  `SEGMENT1` tinyint(3) DEFAULT NULL,
  `SEGMENT2` tinyint(3) DEFAULT NULL,
  `SEGMENT3` tinyint(3) DEFAULT NULL,
  `SEGMENT4` tinyint(3) DEFAULT NULL,
  `SEGMENT5` tinyint(3) DEFAULT NULL,
  `SEGMENT6` tinyint(3) DEFAULT NULL,
  `SEGMENT7` tinyint(3) DEFAULT NULL,
  `SEGMENT8` tinyint(3) DEFAULT NULL,
  `SEGMENT9` tinyint(3) DEFAULT NULL,
  `SEGMENT10` tinyint(3) DEFAULT NULL,
  `SEGMENT11` tinyint(3) DEFAULT NULL,
  `SEGMENT12` tinyint(3) DEFAULT NULL,
  `SEGMENT13` tinyint(3) DEFAULT NULL,
  `SEGMENT14` tinyint(3) DEFAULT NULL,
  `SEGMENT15` tinyint(3) DEFAULT NULL,
  `SEGMENT16` tinyint(3) DEFAULT NULL,
  `SEGMENT17` tinyint(3) DEFAULT NULL,
  `SEGMENT18` tinyint(3) DEFAULT NULL,
  `SEGMENT19` tinyint(3) DEFAULT NULL,
  `SEGMENT20` tinyint(3) DEFAULT NULL,
  `Myokardmasse` smallint(6) DEFAULT NULL,
  `KoronarAnomali` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FunksjonsUndersokelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EndediastoliskVolum` smallint(6) DEFAULT NULL,
  `EndesystoliskVolum` smallint(6) DEFAULT NULL,
  `EjeksjonsFraksjon` tinyint(3) DEFAULT NULL,
  `HjerteminuttVolum` decimal(3,1) DEFAULT NULL,
  `VidereUtredning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CTAngioMedikamenter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Betablokkere` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Nitroglycerin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnetAdjuvant` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `CTTeknikk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProspektivEKG` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DLP` mediumint(9) DEFAULT NULL,
  `Kontrastmiddel` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KontrastmiddelMengde` smallint(6) DEFAULT NULL,
  `Komplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LettAllergisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AlvorligAllergisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hemodynamisk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatus` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_CTAngioVar` (`AvdRESH`,`PasientRegDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `ForlopsOversikt`;
CREATE TABLE `ForlopsOversikt` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientID` int(10) unsigned DEFAULT NULL,
  `Postnr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostSted` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KommuneNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylkenr` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KryptertFnr` char(64) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientKjonn` varchar(11) COLLATE utf8_danish_ci DEFAULT NULL,
  `erMann` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientAlder` bigint(20) DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `Norsktalende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sivilstatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtdanningSSB` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `BasisRegStatus` tinyint(3) DEFAULT NULL,
  `ForlopsType1` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1Num` tinyint(3) DEFAULT NULL,
  `ForlopsType2` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2Num` tinyint(3) DEFAULT NULL,
  `KobletForlopsID` int(10) unsigned DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `OppflgRegStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErOppflg` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgStatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgSekNr` varchar(6) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_ForlopsOversikt` (`AvdRESH`,`HovedDato`,`BasisRegStatus`,`Sykehusnavn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `MitralklaffOppfVar`;
CREATE TABLE `MitralklaffOppfVar` (
  `ForlopsID` int(9) NOT NULL,
  `BasisForlopsID` int(10) unsigned DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BasisScreeningBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BasisProsedyreDato` date DEFAULT NULL,
  `OppfDato` date DEFAULT NULL,
  `OppfType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfAvdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfAvdodDato` date DEFAULT NULL,
  `OppfDodProsRelatert` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `HoydeUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `VektUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gangtest` smallint(6) DEFAULT NULL,
  `GangtestIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kreatinin` smallint(6) DEFAULT NULL,
  `KreatininUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProBNP` mediumint(9) DEFAULT NULL,
  `ProlapsA1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProlapsA2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProlapsA3` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProlapsP1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProlapsP2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProlapsP3` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `VenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aortainsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aortastenose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tricuspidal` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mitralinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mitralstenose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MaxHastighet` tinyint(3) DEFAULT NULL,
  `MiddelgradientMPS` tinyint(3) DEFAULT NULL,
  `Middelgradient` smallint(6) DEFAULT NULL,
  `MRPISA` tinyint(3) DEFAULT NULL,
  `MREROA` smallint(6) DEFAULT NULL,
  `VContracta` decimal(2,1) DEFAULT NULL,
  `FlowRevers` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HoyreVentrikkelTrykk` smallint(6) DEFAULT NULL,
  `HoyreVentrikkelTrykkUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hygiene` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aktiviteter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SmerterUbehag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngstDepresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Helsetilstand` smallint(6) DEFAULT NULL,
  `Komplikasjoner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TIA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Atrieflimmer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Blodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infeksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dialyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DeviceRelKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatus` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_MitralklaffOppfVar` (`AvdRESH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `MitralklaffVar`;
CREATE TABLE `MitralklaffVar` (
  `ForlopsID` int(9) NOT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `ScreeningBeslutning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `BesteBehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Studie` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `HoydeUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `VektUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Royker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KreatininFoer` smallint(6) DEFAULT NULL,
  `KreatininUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProBNP` mediumint(9) DEFAULT NULL,
  `ProBNPUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `HemoglobinFoer` decimal(3,1) DEFAULT NULL,
  `BehHypertoni` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Diabetes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Insulin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Atrieflimmer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfarktSiste90d` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntInnleggelserSisteAar` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntInnleggelserSisteAarUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlHjerteoperasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlACB` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlAVR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlMitralplastikk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlMVR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlAnnet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlKorrigering` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlPCI` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidlHjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KOLS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferKarsykdom` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NYHAKlasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Frailty` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RedusertMobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gangtest` smallint(6) DEFAULT NULL,
  `GangtestIkkeUtfort` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Gripestyrke` smallint(6) DEFAULT NULL,
  `DialyseFoerOp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KritiskPreopTilstand` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hastegrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kontraindikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Porselenaorta` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Malignitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UgunstigAnatomi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Steroidbehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stralebehandling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Thoraxdeformitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvslaattForThorax` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Mobilitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hygiene` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Aktiviteter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SmerterUbehag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AngstDepresjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Helsetilstand` smallint(6) DEFAULT NULL,
  `PreVenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreAortainsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreAortastenose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreTricuspidal` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreMitralstenose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreMitralinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreMaxHastighet` decimal(3,1) DEFAULT NULL,
  `PreMiddelgradient` smallint(6) DEFAULT NULL,
  `PreMREROA` smallint(6) DEFAULT NULL,
  `PreMREROAUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PreHoyreVentTrykk` smallint(6) DEFAULT NULL,
  `STSScore` tinyint(3) DEFAULT NULL,
  `HovedOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndreOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `TredjeOperator` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Operatorer` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `Punksjonstid` time DEFAULT NULL,
  `Avslutningstid` time DEFAULT NULL,
  `IntroducerStr` tinyint(3) DEFAULT NULL,
  `IntroducerStrUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Karlukning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Anestesi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreEkko` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TypeKlaffeprotese` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `VellykketProsedyre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Labnr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Straaledose` decimal(9,2) DEFAULT NULL,
  `StraaledoseUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `GjennomLysTid` varchar(6) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kontrastmiddel` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kontrastmengde` smallint(6) DEFAULT NULL,
  `KontrastmengdeUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompArytmi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompNeurologi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompPacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAkuttKlaff` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAkuttVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAnestesi` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompHLMaskin` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompEmbolisering` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompAnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LabKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dodsdato` date DEFAULT NULL,
  `AvdKomplikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerneslag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerneslagGrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTIA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompTamponade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompPacemaker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAtrieflimmer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompHjerteinfarkt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompVaskular` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodning` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompBlodningGrad` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompInfeksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompDialyse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompAnnenKomp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdKompDod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostUndersokelseForetatt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostKlassifisering` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsA1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsA2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsA3` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsP1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsP2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostProlapsP3` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostVenstreVentrikkelFunksjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostTricuspidal` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMitralstenose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMitralinsuffisiens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMaxgradient` smallint(6) DEFAULT NULL,
  `PostMaxHastighet` decimal(3,1) DEFAULT NULL,
  `PostMiddelgradient` smallint(6) DEFAULT NULL,
  `PostMRPISA` tinyint(3) DEFAULT NULL,
  `PostMRPISAUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostMREROA` smallint(6) DEFAULT NULL,
  `PostMREROAUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostVContracta` decimal(2,1) DEFAULT NULL,
  `PostVContractaUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostReversFlow` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostHoyreVentrikkelTrykk` smallint(6) DEFAULT NULL,
  `PostHoyreVentrikkelTrykkUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MaxKreatinin` smallint(6) DEFAULT NULL,
  `MaxKreatininUkjent` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtskrDato` date DEFAULT NULL,
  `UtskrevetTil` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ASAVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntikoagulantiaVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndrePlatehemmereVedUtskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaStatusHovedskjema` tinyint(3) DEFAULT NULL,
  `SkjemaStatusKomplUtskr` tinyint(3) DEFAULT NULL,
  `SkjemaStatus` int(11) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_MitralklaffVar` (`AvdRESH`,`ProsedyreDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `PasienterStudier`;
CREATE TABLE `PasienterStudier` (
  `PasientID` int(9) NOT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `StudieID` int(9) NOT NULL,
  `StudieNavn` varchar(75) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasInklDato` date DEFAULT NULL,
  `PasAvsluttDato` date DEFAULT NULL,
  `StudieStartDato` date DEFAULT NULL,
  `StudieAvsluttDato` date DEFAULT NULL,
  `StudieOppflgAvslDato` date DEFAULT NULL,
  `StudieStatus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`StudieID`,`PasientID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `SegmentStent`;
CREATE TABLE `SegmentStent` (
  `SegmentID` int(9) NOT NULL,
  `ForlopsID` int(9) NOT NULL,
  `Regtype` varchar(8) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientKjonn` varchar(13) COLLATE utf8_danish_ci DEFAULT NULL,
  `FodselsDato` date DEFAULT NULL,
  `Angiografor1` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor2` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Angiografor3` varchar(101) COLLATE utf8_danish_ci DEFAULT NULL,
  `Indikasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreDato` date DEFAULT NULL,
  `Hoyde` smallint(6) DEFAULT NULL,
  `Vekt` smallint(6) DEFAULT NULL,
  `Segment` tinyint(3) DEFAULT NULL,
  `StentID` int(10) unsigned DEFAULT NULL,
  `Stentnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StentType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BallongLengde` tinyint(3) DEFAULT NULL,
  `DEBDiameter` decimal(4,2) DEFAULT NULL,
  `Diameter` decimal(5,2) DEFAULT NULL,
  `Etterdilatasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LokalSuksess` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Graft` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedikamentellBallong` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MaksTrykkDEB` tinyint(3) DEFAULT NULL,
  `Okklusjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsedyreType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stenttrombosetype` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stenoseklasse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StenoseType` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Stentlengde` smallint(6) DEFAULT NULL,
  `StentSlut` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InflasjonsTidDEB` tinyint(3) DEFAULT NULL,
  `IVLDiameter` decimal(3,2) DEFAULT NULL,
  `AntallPulser` tinyint(3) DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`SegmentID`,`ForlopsID`),
  KEY `idx_SegmentStent` (`AvdRESH`,`ProsedyreDato`,`StentType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `SkjemaOversikt`;
CREATE TABLE `SkjemaOversikt` (
  `Skjemanavn` varchar(18) COLLATE utf8_danish_ci NOT NULL,
  `SkjemaStatus` tinyint(3) DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpprettetDato` timestamp NULL DEFAULT NULL,
  `SistLagretAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistLagretDato` timestamp NULL DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaRekkeflg` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`,`Skjemanavn`),
  KEY `idx_SkjemaOversikt` (`AvdRESH`,`HovedDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;
