---
title: "Veiledning"
params:
  title: "Emty tite"
  author: "Anon author"
  hospitalName: "Ukjent sykehus"
  tableFormat: "html"
  reshId: "999999"
author: "NORIC"
date: '`r format(Sys.time(), "%d. %B %Y")`'

---

# Rapporteket for NORIC `r params$hospitalName`
Rapportekets innhold avhenger av pålogget brukers rolle. 
Vi bruker følgende forkortelser:  

* Systemkoordinator (SC) 
* Lokal koordinator (LC)
* Lokal bruker (LU) 

Der SC har tilgang til alle sykehusets data, LC har noe begrenset tilgang og 
LU kun har tilgang på aggregerte data (månedsrapportene).

### Utforsker 
Her kan LC/SC-brukere ved sykehusene laste inn datasett med sitt sykehus sin
lokale aktivitet. Ansatte i registeret kan laste inn nasjonal aktivitet.
Datasettene kan derettes utforskes i tabell-format eller grafisk format.
__Den enkleste måten å bli kjent med verktøyet på er å prøve seg frem!__

  
Løsningen benytter R-pakken `rpivotTable`.
Det ligger en kort videosnutt som gir et overblikk over hvordan løsningen fungerer [her](https://i0.wp.com/nicolas.kruchten.com/pivottable/images/animation.gif "Videosnutt rpivotTable").
Man kan i tillegg finne mer informasjon om pakken på [hjemmesiden til `rpivotTable`](https://pivottable.js.org/examples/ "Hjemmesiden til rpivotTable"). 

    
### Kodebok 
For LC/SC-brukere. 
Kodeboken inneholder forlaringer til de utledete variablene som finnes i hver av 
tabellene i Utforsker.


### Månedsrapporter 
For LU/LC/SC-brukere. 
Månedsrapporter inneholder oppsummeringer av viktige aktiviteter ved 
enheten det siste året: 

* __Prosedyrer__: Opptellinger relatert til utførte prosedyrer fra 
_Andre prosedyrer_ - og _AngioPCI_-modulen. Inneholder også opplysninger om 
hvilke stenter som er brukt.

* __Aktivitet__ (Kun for SC-rolle): Inneholder opptellinger av angiograførenes 
og operatørenes aktivitet.


### Datadump
SC-rolle. 
Nedlasting av datadumper (excel-format) som inneholder rådata. 

### Abonnement 
LU/LC/SC-rolle.
Her kan man administrere sine abonnement på månedsrapportene. 
Man kan selv velge frekvens (ukentlig, månedlig, kvartal, ...) og ønsket 
format (html eller pdf).

### Verktøy
Brukere med SC-rolle har tilgang på følgende verktøy:

* __Metadata__: Denne siden inneholder metadata ("data om data") om de 
forskjellige tabellene som utgjør datagrunnlaget for Rapporteket 
(AndreProsedyrerVar, AngioPCIVar osv.). Hvis man for eksempel lurer på om 
datadumpen *SegmentStent*  har en variabel som heter "Okklusjon", så kan man
bruke søkeordet "okklusjon" i søkeboksen oppe i høyre hjørne. 
Merk at disse tabellene er et resultat av spørringer mot databasen. 
Tabellene har derfor ikke samme struktur og variabelnavn som databasen. 

* __Eksport__: Tilgjengelig kun for statistikerne i registeret. 

* __Utsendinger__ : Her kan ansatte i registeret administrere utsending av
månedlige resultater per sykehus, sammenlignet med nasjonale tall. 

* __Bruksstatistikk__: Her kan ansatte i registeret holde oversikt over 
innlogginger og annen aktivitet på Rapporteket. 

* __Nedlasting rapporter__: Her kan ansatte i registeret hente de månedlige
resultatene for sykehusene.

### Kontaktinformasjon
Ta gjerne kontakt ved spørsmål eller innspill til rapporter eller annet
innhold på rapporteket. E-post: noric@helse-bergen.no
